### ISSUE TITLE
OSGi Environment Eclipse Update-Site Version 2.3 corrupt

### ISSUE THREAD

**Issue by ggrune** [restlet/restlet-framework-java#1001]
The update site definition on http://p2.restlet.com/2.3 referes to a version 2.3.0.snapshot-v20140918-1456 but the site contains only jars for version 2.3.0.snapshot-v20141217-1648
Please update the definition.

**Comment by thboileau** [comment]
Hello @ggrune , thanks for reporting this issue. This must be fixed now.
