### ISSUE TITLE
Restlet in Apache Felix

### ISSUE THREAD

**Issue by kugtong33** [restlet/restlet-framework-java#1013]
I am deploying a Restlet application in the Apache Felix environment and I am using `Protocol.HTTP` but it threw a warning and there are no http server running.

```
Jan 22, 2015 1:04:29 PM org.restlet.engine.Engine createHelper
WARNING: No available server connector supports the required protocols: 'HTTP' . Please add the JAR of a matching connector to your classpath.
```

This is the code of the Restlet server:
```java
Component component = new Component();
Server server = new Server(Protocol.HTTP, 8080);
server.setName("Sample Server");
server.setNext(new SampleApplication());
component.getServers().add(server);
component.start();
```

These are the following tools I am using
```
Restlest 2.3.0
Apache Felix 4.4.1
Apache Felix iPOJO 1.12.0
OS: Ubuntu 14.04 64-bit
Java 1.8.0_25
```

Could you guys help me?

Thanks in advance.

**Comment by templth** [comment]
Hello,

I mean that it depends where you put the processing to create the component. In fact, the bundle containing server connectors need to be started before the bundle of restlet core itself.

You can use start levels to configure this or put the code to create the Restlet component in a framework listener to be sure that all bundles are started:

```
public void start(BundleContext bundleContext) throws Exception {
    this.context.addFrameworkListener(new FrameworkListener() {
        public void frameworkEvent(FrameworkEvent event) {
            if (event.getType() == FrameworkEvent.STARTED) {
                Component component = new Component();
                Server server = new Server(Protocol.HTTP, 8080);
                server.setName("Sample Server");
                server.setNext(new SampleApplication());
                component.getServers().add(server);
                component.start();
            }
        }
    });
}
```

Thierry

**Comment by thboileau** [comment]
Nb:
I have a remark regarding the way you attach your application.

I would do the following instead:
```java
Component component = new Component();
component.getServers().add(Protocol.HTTP, 8080);
component.getDefaultHost().attach(new SampleApplication());
component.start();
```
Then the `SampleApplication` defines a name.

**Comment by kugtong33** [comment]
Thanks guys for you response.

@templth:
What do you mean at 'it depends where you put the processing to create the component'?
Currently I am using the code in an ipojo bundle but there are problems using the `BundleActivator` so instead I put it this way using ipojo annotations:

```java
@Validate
public void start() throws Exception{
    Component component = new Component();
    Server server = new Server(Protocol.HTTP, 8080);
    server.setName("Sample Server");
    server.setNext(new SampleApplication());
    component.getServers().add(server);
    component.start();
}
```

And I implemented the Restlet library in the Apache Felix by using `bundle:bundle` goal of the `maven-bundle-plugin` and exported its contents.

@thboileau:
I created it that way because I will be adding multiple servers with different ports each. Is it recommended to do it that way or should I use `ServerList` ?

So I have some follow up questions
- What are these bundles containing server connectors that I should start first before the bundle of Restlet core itself?
- Is it acceptable that I wrapped the Restlet libraries into an OSGi bundle or are there any existing OSGi Restlet bundles that I can use?

**Comment by thboileau** [comment]
@kugtong33, do you mean that you will segregate applications by port?
In that case, you can use the [VirtualHost](http://restlet.com/technical-resources/restlet-framework/javadocs/2.3/jse/api/) instead.
It allows to filter on several parameters (domain, server port, etc) and attach several applications.
```java
        VirtualHost vh = new VirtualHost();
        vh.setServerPort("8080");
        vh.attach("/app", new SampleApplication());
        vh.attach("/app2", new SampleApplication2());
        c.getHosts().add(vh);
```

**Comment by templth** [comment]
@kugtong33 Yes an activator is definitevely the right place to put your code ;-) However we need to take care about the Restlet auto-registration of connectors. These connectors are registered when Restlet extension bundles are loaded. So, for example, if the bundle `org.restlet` and your bundle (contained your previous code) is loaded before the `org.restlet.ext;jetty`, the jetty server connector wasn't available for your component. At this level, start levels and / or OSGI framework listeners can help you...

**Comment by kugtong33** [comment]
@templth 
If we will run the application normally(not using osgi based frameworks), what server connector it will use or are there server connectors embedded in Java 8?

What is the default server connector or is jetty the default connector?
The Restlet core uses `com.sun.net.httpserver`, Is it a server connector?

@thboileau 
Then the urls will be `http://localhost:8080/app` and `http://localhost:8080/app2` , I will decide after I implement proxy pass using nginx/apache

**Comment by kugtong33** [comment]
@templth 
I am now experimenting your `Restlet` release for `OSGi Environments`, as usual I can download it but does `Restlet` has its `Bundle Repository` like `http://felix.apache.org/obr/releases.xml`  or like `mvn:org.apache.karaf.features/standard/4.0.0.M1/xml/features` ?

Sorry for the excessive questions, maybe I am now in the right track for the OSGi release. :+1: 

Thanks for the help guys!

**Comment by thboileau** [comment]
Hi,
you can find the osgi edition in the maven repository (http://maven.restlet.com/), using the group id "org.restlet.osgi".You can have a look here: http://maven.restlet.com/org/restlet/osgi/
The bundles are also available in a eclipse update site: http://p2.restlet.com/2.3/
I note the idea of a bundle repository, that sounds a good idea.

**Comment by templth** [comment]
@kugtong33 I don't know exactly for the default server connector... I heard that the internal server connector (nio) wasn't in the core restlet module anymore (in the version 2.3). To be sure, have a look at the list of the connector within your current engine:

```
Engine.getInstance().getRegisteredServers()
```

**Comment by kugtong33** [comment]
The `Restlet Osgi` release answers the issue and it is working fine thanks for the help guys! and by the way, the bundle repository would be so much of help :+1:
