### ISSUE TITLE
Missing org.restlet.jse:org.restlet.lib.swagger-models:1.5.0-SNAPSHOT/maven-metadata.xml

### ISSUE THREAD

**Issue by jlouvel** [restlet/restlet-framework-java#1016]
While building this project (https://github.com/restlet/restlet-tutorial/blob/master/modules/org.restlet.tutorial.webapi/pom.xml), I got a Maven download error:

Downloading: https://source.db4o.com/maven/org/restlet/jse/org.restlet.lib.swagger-models/1.5.0-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata org.restlet.jse:org.restlet.lib.swagger-models:1.5.0-SNAPSHOT/maven-metadata.xml from/to maven1-java (http://download.java.net/maven/1): Cannot access http://down
load.java.net/maven/1 with type legacy using the available connector factories: BasicRepositoryConnectorFactory
[WARNING] Could not transfer metadata org.restlet.jse:org.restlet.lib.swagger-models:1.5.0-SNAPSHOT/maven-metadata.xml from/to maven-db4o (https://source.db4o.com/maven/): sun.security.validator.Valid
atorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[WARNING] Failure to transfer org.restlet.jse:org.restlet.lib.swagger-models:1.5.0-SNAPSHOT/maven-metadata.xml from http://download.java.net/maven/1 was cached in the local repository, resolution will
 not be reattempted until the update interval of maven1-java has elapsed or updates are forced. Original error: Could not transfer metadata org.restlet.jse:org.restlet.lib.swagger-models:1.5.0-SNAPSHO
T/maven-metadata.xml from/to maven1-java (http://download.java.net/maven/1): Cannot access http://download.java.net/maven/1 with type legacy using the available connector factories: BasicRepositoryCon
nectorFactory
[WARNING] Failure to transfer org.restlet.jse:org.restlet.lib.swagger-models:1.5.0-SNAPSHOT/maven-metadata.xml from https://source.db4o.com/maven/ was cached in the local repository, resolution will n
ot be reattempted until the update interval of maven-db4o has elapsed or updates are forced. Original error: Could not transfer metadata org.restlet.jse:org.restlet.lib.swagger-models:1.5.0-SNAPSHOT/m
aven-metadata.xml from/to maven-db4o (https://source.db4o.com/maven/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException:
 unable to find valid certification path to requested target

**Comment by thboileau** [comment]
Actually, this is just a warning, this is not blocking. Maven tries to retrieve this artifact from db4o maven.
