### ISSUE TITLE
OSGI download redirects to http://localhost:12000/

### ISSUE THREAD

**Issue by jrwilliams** [restlet/restlet-framework-java#1017]
I'm trying to download the stable OSGi zip from here: http://restlet.com/downloads/current/#release=stable&edition=osgi&distribution=zip but when I click the "Download 2.3.0" button, I get redirected to localhost:12000.

I've tried downloading all other editions, and they work fine.

**Comment by thboileau** [comment]
Hello @jrwilliams,
Thanks a l ot for reporting this issue, it has been fixed.
