### ISSUE TITLE
Problem when using the CORS filter with authentication

### ISSUE THREAD

**Issue by templth** [restlet/restlet-framework-java#1019]
There is a problem when trying to use the CorsFilter with an authentication. This post of StackOverFlow describes the problem: http://stackoverflow.com/questions/28196426/restlet-corsfilter-with-challengeauthenticator.

I think that we should use the method `beforeHandle` instead of `afterHandle` in the CorsFilter class.

**Comment by boillodmanuel** [comment]
I link this SOF thread which concerns this use case: http://stackoverflow.com/questions/15734031/why-does-the-preflight-options-request-of-an-authenticated-cors-request-work-in

**Comment by thboileau** [comment]
Added answer to SOF thread.
closing.
