### ISSUE TITLE
documentation bug - faulty link

### ISSUE THREAD

**Issue by komasoftware** [restlet/restlet-framework-java#1021]
On this page http://restlet.com/technical-resources/restlet-framework/guide/2.3/extensions/swagger 
there is a link to a example project with text "this code" that links to http://learn/archives/examples/swagger/SwaggerApplicationExample.zip 

That gives a 404.

**Comment by thboileau** [comment]
Hi @komasoftware, thanks for reporting this. I hope a fiw will be available soon...
Here is the right URL:
http://restlet.com/technical-resources/restlet-framework/archives/examples/swagger/SwaggerApplicationExample.zip

**Comment by thboileau** [comment]
I close this issue.
