### ISSUE TITLE
allow maven build from top source directory

### ISSUE THREAD

**Issue by krichter722** [restlet/restlet-framework-java#1026]
Currently it is necessary to build with `ant` and in the `build` subdirectory and there're also some `pom.xml` files and everything is explained in `build/readme.txt`. It'd be much nicer to provide a `pom.xml` in the top source directory which does everything self explanatory.

**Comment by thboileau** [comment]
It could be nice also to migrate to Maven structure: #5

**Comment by jlouvel** [comment]
One idea we have to achieve this goal is to split the current GitHub repository into 2 repositories:
 - one for the source code including valid Maven POMs for each module
 - another for the libraries including the official Ant build script capable of building the multi-editions/distribution deliverables

This would facilitate building and contributions from the community based on Maven conventions, reducing the size of the GitHub repo to clone, while preserving the full build capabilities via a second repo.

**Comment by jlouvel** [comment]
Finally, starting with 2.5 RC1, Restlet Framework is published in Maven Central. Thanks all for your interest in making this happen, it took quite a lot of effort to achieve. See announcement https://github.com/restlet/restlet-framework-java/discussions/1434
