### ISSUE TITLE
PUT and POST not working from J2SE platform (RESTLET Version 3.0-M1)

### ISSUE THREAD

**Issue by rcbeuker** [restlet/restlet-framework-java#1029]
I'm working on a project with GWT and J2SE clients. The GWT part is working great, but now there are problems with the J2SE client;
```
"The server understands the content type of the request entity and the syntax of the request entity is correct but was unable to process the contained instructions"


"The serialized representation must have this media type: application/x-java-serialized-object or this one: application/x-java-serialized-object+xml"
```

![screen shot 2015-02-19 at 11 56 26](https://cloud.githubusercontent.com/assets/8544013/6265424/73d71a64-b82e-11e4-822e-05634154b860.png)

This code was working some months/versions ago... Both PUT and POST produce this error while GET is working. Whats wrong here? 

Here's a really simple test case

// Shared Interface 
```
public interface J2SeClientServerResourceInt
{
    @Post("json")
    public J2seStatusDto postJ2seStatus(J2seStatusDto pJ2seStatusDto);
}
```
// Java Bean
```
public class J2seStatusDto implements Serializable
{
    private static final long serialVersionUID = 6901448809350740172L;

    private String mTest;
    
    public J2seStatusDto()
    {
    }
    
    public J2seStatusDto(String pTest)
    {
        setTest(pTest); 
    }

    public String getTest()
    {
        return mTest;
    }

    public void setTest(String pTest)
    {
        mTest = pTest;
    }
}
```
// Server 
```
public class J2seServerResource extends ClaireServerResource implements J2SeServerResourceInt
{
    @Override
    public J2seStatusDto postJ2seStatusDto(J2seStatusDto pJ2seStatusDto)
    {
        return pJ2seStatusDto;
    }
}
```
// J2SE Client 
```
public class ClaireJsSeTestClient
{
    public static void main(String[] args)
    {
        Reference lReference = new Reference("http://localhost:8888//rest/j2se");
        ClientResource lClientResource = new ClientResource(lReference);
        lClientResource.accept(MediaType.APPLICATION_JSON);
        J2SeServerResourceInt lJ2SeServerResource = lClientResource.wrap(J2SeServerResourceInt.class);
        J2seStatusDto lJ2seStatusDto = new J2seStatusDto("TEST");
        J2seStatusDto lJ2seResultDto = lJ2SeServerResource.postJ2seStatusDto(lJ2seStatusDto);
    }
}
```
// Maven J2Se Client
```
   <dependencies>
        <dependency>
            <groupId>org.restlet.jse</groupId>
            <artifactId>org.restlet</artifactId>
            <version>3.0-M1</version>
        </dependency>
        <dependency>
            <groupId>org.restlet.jse</groupId>
            <artifactId>org.restlet.ext.jackson</artifactId>
            <version>3.0-M1</version>
        </dependency>
    </dependencies>
```

// Maven GAE Server
```
       <dependency>
            <groupId>org.restlet.gae</groupId>
            <artifactId>org.restlet</artifactId>
            <version>3.0-M1</version>
        </dependency>
        <dependency>
            <groupId>org.restlet.gae</groupId>
            <artifactId>org.restlet.ext.servlet</artifactId>
            <version>3.0-M1</version>
        </dependency>
        <dependency>
            <groupId>org.restlet.gae</groupId>
            <artifactId>org.restlet.ext.jackson</artifactId>
            <version>3.0-M1</version>
        </dependency>
        <dependency>
            <groupId>org.restlet.gae</groupId>
            <artifactId>org.restlet.ext.gwt</artifactId>
            <version>3.0-M1</version>
        </dependency>
        <dependency>
            <groupId>org.restlet.gwt</groupId>
            <artifactId>org.restlet</artifactId>
            <version>3.0-M1</version>
            <scope>compile</scope>
        </dependency>
```

**Comment by rcbeuker** [comment]
When debugging with breakpoints in the J2seServerResource, a PUT request reaches the server with payload NULL and a POST doesn't even reach the server (and give the error message). A GET request works fine...

**Comment by rcbeuker** [comment]
When tested with Chrome REST Console the server works fine, the J2SE Client is the problem...

https://chrome.google.com/webstore/detail/rest-console/cokgbflfommojglbmbpenpphppikmonn?hl=en

**Comment by rcbeuker** [comment]
Switching from JSON to XML gives the same results...

**Comment by rcbeuker** [comment]
Anyone?!? PUT and POST from J2SE platform are basic functionality ...

**Comment by jlouvel** [comment]
Is this working with version 2.3.1? 

Something might have been broken in the early 3.0 milestone 1.

**Comment by rcbeuker** [comment]
Hello Jerome,

No the prior version(s) 2.3.1 complains about the content length;

![screen shot 2015-02-22 at 18 32 38](https://cloud.githubusercontent.com/assets/8544013/6319581/3d8dce5e-bac1-11e4-8fb2-1e3e07ae0acc.png)

Regards

Roland

**Comment by rcbeuker** [comment]
No updates on this situation? Is this a fault from our side or is the problem reproducible? Right now, all our J2Se clients are down... :(

**Comment by thboileau** [comment]
Hello,

we are quite busy at this time. I will answer you more appropriately
tomorrow.

Best regards,

2015-02-25 15:24 GMT+01:00 rcbeuker <notifications@github.com>:

> No updates on this situation? Is this a fault from our side or is the
> problem reproducible? Right now, all our J2Se clients are down... :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/restlet/restlet-framework-java/issues/1029#issuecomment-75967491>
> .
>



-- 
*Thierry Boileau, Mr B*
+1 (408) 387-3184 • tboileau@restlet.com

<http://restlet.com/>
6 Rue Rose Dieng-Kuntz • Nantes, 44300 • France

**Comment by thboileau** [comment]
I've made the following tests:

RF version | app | client | result (get and post)
---------------|------|--------|---------------------------
2.3.1 | dev server | GWT | OK
2.3.1 | dev server | JSE | OK
2.3.1 | GAE server | GWT | 
2.3.1 | GAE server | JSE | 
3.0 M1 | dev server | GWT | OK
3.0 M1 | dev server | JSE | OK
3.0 M1 | GAE server | GWT | 
3.0 M1 | GAE server | JSE |

**Comment by rcbeuker** [comment]
Hello Jerome,

Indeed it was just one extra line of code to fix this;
```
cr.setRequestEntityBuffering(true);
```
Where did this come from? We totally overlooked this...

Thanks for your time and support!

Best regards,

Roland

**Comment by thboileau** [comment]
It comes from a constraint of the GAE platform (here is a pointer: https://code.google.com/p/googleappengine/issues/detail?id=129). The buffering of the request entity has been provided by Restlet Framework version 2.1 M4.
It works for GWT requests because the requests are handled by the browser which seems to compute the size of the sent entity. Regarding the other requests coming from the jse client, I don't really understand why  it worked at some time.

**Comment by rcbeuker** [comment]
The problem started when the project started mixing GWT and J2SE clients.
At this point we had to add the JSON setting and the problem showed up....

But (indeed) when falling back to old versions the problem kept
appearing... Maybe the developer from the first J2SE clients used a non GAE
server for his tests.
Op 27 feb. 2015 09:18 schreef "Thierry Boileau" <notifications@github.com>:
