### ISSUE TITLE
Misspelled CORS header breaks behaviour

### ISSUE THREAD

**Issue by q7a** [restlet/restlet-framework-java#1030]
When XHR request is made against Restlet 2.3.1 with `withCredentials` set to `true`, Restlet returns misspelled `Access-Control-Allow-Credential` header instead of correct `Access-Control-Allow-Credentials` (singular v plural) which gets rejected by the browser thus preventing communication.

Fixing typo in `HeaderConstants.java` should be enough but this is misspelled in many comments so may be worth fixing there too. 

References:
* http://www.w3.org/TR/cors/#access-control-allow-credentials-response-header
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Requests_with_credentials

**Comment by boillodmanuel** [comment]
Fixed in branch 2.3. 

Thanks for reporting this issue.

**Comment by q7a** [comment]
@boillodmanuel  Thanks a lot for prompt fix.

Shouldn't this also land in the master to avoid regression in the future? Thanks again.

**Comment by thboileau** [comment]
yes, I take care of that.
