### ISSUE TITLE
Extend GaeAuthenticator class to take into account admin role

### ISSUE THREAD

**Issue by templth** [restlet/restlet-framework-java#1036]
See this answer on StackOverFlow for more details: http://stackoverflow.com/questions/28936580/using-google-authentication-with-restlet.

**Comment by komasoftware** [comment]
Isn't [GaeEnroler](http://restlet.com/technical-resources/restlet-framework/javadocs/2.3/gae/ext/org/restlet/ext/gae/GaeEnroler.html) doing this already ?

**Comment by templth** [comment]
Added a PR. See https://github.com/restlet/restlet-framework-java/pull/1037.

**Comment by templth** [comment]
@komasoftware Yes, you're right! I didn't see this class...

**Comment by templth** [comment]
Closing
