### ISSUE TITLE
tomcat shutdown

### ISSUE THREAD

**Issue by jpstratton** [restlet/restlet-framework-java#1053]
Tomcat does not shutdown because the four restlet threads started are not daemon threads.  Workaround was to add setDaemon to method in TaskService.java.  Is there a better way?

```java
public Thread newThread(Runnable runnable) {
    Thread t = factory.newThread(runnable);

    // Default factory is documented as producing names of the
    // form "pool-N-thread-M".
    t.setName(t.getName().replaceFirst("pool", "restlet"));
    t.setDaemon(true);
    return t;
}
```

**Comment by thboileau** [comment]
hi @jpstratton , could you precise the version of the framework?

**Comment by jpstratton** [comment]
I am using version 2.3.1.
At 01:11 AM 4/14/2015, Thierry Boileau wrote:
hi
@jpstratton , could you
precise the version of the framework?
�
Reply to this email directly or

view it on GitHub.

**Comment by jpstratton** [comment]
We use tomcat 8 with JDK 8.  When the system starts restlet creates four threads and by default they are not daemon threads.  Adding the one line to set the threads daemon allow tomcat 8 to shutdown.  I tried to set the attribute controllerDaemon to true but that did not help.

**Comment by thboileau** [comment]
checked with @jlouvel , ok for the fix.

**Comment by thboileau** [comment]
Thanks @jpstratton  for reporting this issue.
Added a "daemon" property that allows the TaskService, true by default.
It will be part of 2.3.2 coming soon.
