### ISSUE TITLE
What are the annotations in Restlet framework?

### ISSUE THREAD

**Issue by ggeetha** [restlet/restlet-framework-java#1056]
What are the Restlet Annotations available for API Versioning? And also How to map the version from the API with my source code?

If my API looks like this : http://localhost:8080/example.com/v2/hello
Then In my source code how to map the version with appropriate functionality?
For example :
```java
If(version == 1) {//Do Version 1 Source Code}
else If(version == 2) {//Do Version 2 Source Code}
else If(version == 3) {//Do Version 3 Source Code} ………..
```
If I did like this, Then why we are going for Versioning. We can implement Manually Right? And also If I have to add some 100 versions, then the code looks uglier and it becomes lengthier.
I get confused how to map the version in Source Code. Please Clarify my doubt.

I have read that we can use annotations for handling API versioning. But I don't know what are the annotations available in restlet framework. Please let me know.
Regards,
Geetha.

**Comment by thboileau** [comment]
Hello Geetha,
there is no annotations in Restlet Framework dedicated to versioning, but if you plan to version your URIs there are some solutions.

In order to illustrate these solutions, we imagine an application with a single "hello" resource: having this path: `/hello`.
 
The first implementation of the application is the following:
```java
public Restlet createInboundRoot() {
    Router router = new Router(getContext());
    router.attach("/hello", HelloServerResource.class);
    return router;
}
```

Then we want to support versioning via the URI.



1. Basic solution, handle all versions in the same server resource class.

```java
public Restlet createInboundRoot() {
    Router router = new Router(getContext());
    router.attach("/{version}/hello", HelloServerResource.class);
    return router;
}
```

this leads to this pattern, in the resource class.
```java
version = getAttribute("version");
If(version == 1) {//Do Version 1 Source Code}
else If(version == 2) {//Do Version 2 Source Code}
else If(version == 3) {//Do Version 3 Source Code} ………..
```

2. have distinct classes

```java
public Restlet createInboundRoot() {
    Router router = new Router(getContext());

    router.attach("/v1/hello", com.example.resource.HelloServerResourceV1.class);
    router.attach("/v2/hello", com.example.resource.HelloServerResourceV2.class);

    return router;
}
```

3. have distinct packages, 

```java
public Restlet createInboundRoot() {
    Router router = new Router(getContext());

    router.attach("/v1/hello", com.example.resource.v1.HelloServerResource.class);
    router.attach("/v2/hello", com.example.resource.v1.HelloServerResource.class);

    return router;
}
```

4. have router by version of API

```java
public Restlet createInboundRoot() {
    Router router = new Router(getContext());

    router.attach("/v1", createV1Router());
    router.attach("/v2", createV2Router());

    return router;
}

public Router createV1Router() {
    Router router = new Router(getContext());
    router.attach("/hello", com.example.resource.v1.HelloServerResource.class);

    return router;
}
```

**Comment by jlouvel** [comment]
Great explanation @thboileau!
Could we create an "API versionning" page under "Part 2 - Core Restlet / Routing package"?

**Comment by jlouvel** [comment]
See related HackerNews discussion:
https://news.ycombinator.com/item?id=9407776

**Comment by thboileau** [comment]
Hi @jlouvel , I keep this ticket open in order to update documentation.

**Comment by ggeetha** [comment]
Yeah, thboileau. I did the same thing that you have explained. But what happened was, If I use "if-else", then, if my application grows to 15 versions for example, then the code looks lengthier right? How to overcome this?

**Comment by thboileau** [comment]
I'm sorry @ggeetha , the framework doesn't address such issue, and I'm not sure the other ones (such as jersey, etc) too. To my mind, it's much more a developer problem.
For good reasons, your code is becoming more and more complex leading you to handle several versions of your API. Then, you're right, your code will be lengthier. At the beginning, it may be fine to handle such (little) complexity inside the ServerResource sub-classes, but I'm pretty sure that it won't scale. I think that maintenance will be easier, at the end, by partitioning at a higher level. Having said, you can start with the if/else pattern, if maintenance is fine. With the time and as the code will grow, I'm sure you will refactor it.

**Comment by thboileau** [comment]
if you agree, we will close this issue.

**Comment by ggeetha** [comment]
Yeah. I will try to think some other way to solve this. Thank you @thboileau. We can close this issue.

**Comment by thboileau** [comment]
ok, closing.
