### ISSUE TITLE
Complete ResourceException with Request and Response attributes.

### ISSUE THREAD

**Issue by thboileau** [restlet/restlet-framework-java#1063]
Such enhancement should ease the handling of errors.

**Comment by jlouvel** [comment]
Sounds like a good idea, but IMO not for RF 2.3 due to the public API impacts. Can you merge this in master?

**Comment by boillodmanuel** [comment]
Commit pushed on branch `apispark-3.8` with no API impacts.

**Comment by thboileau** [comment]
`ResourceException` class gives now access to request/response and is instantiated with the related resource.
