### ISSUE TITLE
A problem with the JaxRsClientResource with HTTP POST web services

### ISSUE THREAD

**Issue by edouardmercier** [restlet/restlet-framework-java#1072]
Hello.

While attempting to play with the `JaxRsClientResource` in order to invoke web services developed with Restlet v2.3.2, running in GAE flavor, following the JAX-RS paradigm, I went into an issue when attempting to run a `POST` HTTP method. The HTTP `GET` web services are fine, however.

Let's say that my JAX-RS web service interface is something like
```
@Path("account")
@Produces({ MediaType.APPLICATION_JSON })
public static interface IAccountResource
{
  @POST
  @Path("create")
  void create(@QueryParam("email") String email);
}
```
As soon as I attempt to invoke that method through the `JaxRsClientResource`, the body of the POST method is set with the `Representation` of the single `email` parameter and the `Content-Length` of the resulting HTTP request is not defined, hence causing the GAE to reject the request.

I have taken a look at the source code and the `ClientInvocationHandler.invoke()` seems to be responsible for that bad behavior: it invokes the `request.setEntity(requestEntity);` method, providing a `requestEntity` which has been computed for the query parameters…

I am not 100 % tu understand what is going under the hood. Could you have a look at it, please? Is there a specific think to do in order to have the HTTP `POST` JAX-RS web services to work?

Thank you for your support.

**Comment by thboileau** [comment]
Hi @edouardmercier, when issuing calls to resources hosted by the GAE platform, you must ask the client resource to buffer the entity in order to compute the content-length.
Just call the `setRequestEntityBuffering` method with the `true` value.

**Comment by edouardmercier** [comment]
Thank you so much @thboileau: I was not aware of this `ClientResource.setRequestEntityBuffering()` method, which actually enables the caller to compute the HTTP `Content-Length` header. This now works like a charm.

However, as I mentioned, even if the `POST` body should be empty, the HTTP request is done with a body corresponding to the last `@QueryParam` text representation, which is very likely to be a bug, but which does not prevent the request to be run: could you take a look at this, please?

Thank you for your valuable help and work.

**Comment by thboileau** [comment]
Hi @edouardmercier ,
Thanks a lot for reporting this issue, I've added a fix and also took into account FormParam annotations.
It will be part of release 2.3.3.

Best regards

**Comment by edouardmercier** [comment]
Thank you @thboileau.

**Comment by theprivateland** [comment]
Cant get this sorted and serviceStatus setter aint catching everything, any updates on this?
