### ISSUE TITLE
How to send POST requests using JaxRsClientResource

### ISSUE THREAD

**Issue by thboileau** [restlet/restlet-framework-java#1081]
mail sent by Hassene Ben Amara

> I am facing a problem to create a Restlet client using JAXRS annotated resource class.
> Snippet from Resource:
> 
> ``` java
>     @POST
>     @Path("/getLoginAppInfo")
>     @Consumes("application/xml")
>     @Produces("application/xml")
>     public GetLoginAppInfoResponse getLoginAppInfo(
>             GetLoginAppInfoRequest request);
>     @POST
>     @Path("/appLogin")
>     @Consumes("application/xml")
>     @Produces("application/xml")
>     public AppLoginResponse appLogin(AppLoginRequest request);
> ```
> 
> On my restlet client, I am using this code:
> 
> ``` java
> IAppLoginResource resource = JaxRsClientResource.createJaxRsClient("http://localhost:9090/rest", IAppLoginResource.class);          
> final GetLoginAppInfoResponse response = resource.getLoginAppInfo( getLoginAppInfoRequest );
> ```
> 
> When I check the issued HTTP call, it's of type GET.
> How do I set the HTTP call to POST using JaxRsClientResource?
> Any help (or snippet of code) would be highly appreciated.
> NB: I took a look at this link Referring to this post here https://github.com/restlet/restlet-framework-java/issues/1072  but it didnt help much.

**Comment by thboileau** [comment]
I've tested your interface (by removing the `consumes` and `produces` annotations which are not taken into account by the jax-rs client, as I notice in the source code. and it works for me.

**Comment by hbenamara** [comment]
Hi Thierry,

Thank you very much for your help!
I do have the @Path("/applogin") annotation already at the interface level, I removed the consume and produce as u suggested but still the HTTP request issued is of type GET.

Can you please share your working version, I might be missing something.

thanks

**Comment by thboileau** [comment]
Hi @hbenamara , I send you my sample Eclipse project.

**Comment by thboileau** [comment]
quite old ticket.
Let's close it.
