### ISSUE TITLE
@POST Method with JAX-RS does not work correctly.

### ISSUE THREAD

**Issue by theprivateland** [restlet/restlet-framework-java#1094]
I have been trying and testing but this is just very hard, tried everything, I think it's just not stable enough.

When you submit any form with JAX-RS mapping using @POST annotation, all form fields annotated with @FormParam are null.

It just does not work at all. Its quite critical as making removing restlet from use (really trying hard to keep using it as api is very nice for other parts).

**Comment by theprivateland** [comment]
Anyone? Its quite critical.

**Comment by thboileau** [comment]
Hi @theprivateland ,

I've tried the following and it works for me using curl:

The server resource class:
```java
@Path("/test")
public class TestServerResource {

    @POST
    public String testPost(@FormParam("value") String form) {
        return "Value taken from form " + form;
    }

}
```

The curl command line:
```
curl --data "value=myvalue" http://localhost:9090/test
```

**Comment by thboileau** [comment]
Having said that the jaxrs client is bugged.
The following does not work as the client just send the value, and not a real form.
```java
        TestResource resource = JaxRsClientResource.createJaxRsClient("http://localhost:9090", TestResource.class);
        System.out.println(resource.testPost("myvalue"));
```

**Comment by theprivateland** [comment]
I tried and I have null... I have some filters set etc, but with jersey there are no nulls.

Screen from postman:



I'll try with all filters disabled etc. 

Peter Fronc
Software Engineer

Mobile: +44 75 74 94 54 64
E: peter@theprivateland.com <mailto:peter.fronc@qubitdigital.com>
Skype: piotrek.fronc

**Comment by thboileau** [comment]
Hi @theprivateland , I've tried with this signature for the interface and it works for me. I send you my eclise project:

```java
@Path("/test")
public interface TestResource {

    @POST
    public String testPost(@FormParam("test") String form);
}
```

**Comment by thboileau** [comment]
I've sent you my sample project that works with the current state of the 2.3 branch, which is the 2.3.2 release + some fixes, especially this one: c1698622d5b1d22b4aabdd8daaf168dc91fc7e17 
The next release will be available in a few days.

**Comment by theprivateland** [comment]
Thanks, I will re-check everything, it may be something odd. Maybe some jars conflict. If you get the value it may be something wring in my setup, no magic in java.


Peter Fronc
Software Engineer

Mobile: +44 75 74 94 54 64
E: peter@theprivateland.com <mailto:peter.fronc@qubitdigital.com>
Skype: piotrek.fronc

**Comment by theprivateland** [comment]
One more thing, Im deploying app with servlet mechanism, not standalone app, it may be worth checking with tomcat instance.

Jars included:




Peter Fronc

Software Engineer

Mobile: +44 75 74 94 54 64
E: peter@theprivateland.com <mailto:peter.fronc@qubitdigital.com>
Skype: piotrek.fronc

**Comment by theprivateland** [comment]
I got it now! It set's null when:
Content-Type:application/x-www-form-urlencoded

Is set! IF I set raw value:

Content-Type:text/plain;charset=UTF-8

I get the form param in!

Please see screens below:



And the null:




Clearly, form headers settings are damaged. Can it be fixed? It's quite urgent to me. I don't wanna roll back top old dodgy jersey.



Peter Fronc
Software Engineer

Mobile: +44 75 74 94 54 64
E: peter@theprivateland.com <mailto:peter.fronc@qubitdigital.com>
Skype: piotrek.fronc

**Comment by peterfronc** [comment]
I will keep posting directly in here, I can see some odd mail handling from git.

**Comment by peterfronc** [comment]
Can you remove please my contact details? (just delete all messages, Ill add full summary below).

**Comment by peterfronc** [comment]
The core of issue seems to be related to Content-Type headers, the values are set only for raw text values.
It set's null when:
Content-Type:application/x-www-form-urlencoded

If I set header to raw value:

Content-Type:text/plain;charset=UTF-8

I get the form parameter.

Clearly, form headers settings are damaged. Can it be fixed? It's quite urgent to me. I don't wanna roll back top old dodgy jersey.

(For some reasons I cant attach screens).

**Comment by peterfronc** [comment]
Sorry for switching accounts (i have two profiles). Anyway, I think something is definitely buggy, I checked requests at filter levels and they all contain values. When it reaches the service - any thing else than raw content type is nulled - it applies for any method (PUT as well).

**Comment by peterfronc** [comment]
I'll be patiently awaiting for the release. I could use forms but its about moving away from jersey, I would have to re-implement 20 classes with plenty of services.

**Comment by thboileau** [comment]
Hi @peterfronc, the content-type header is correct.
By using the @FormParam annotation, it really sends a web form, denoted by the "application/x-www-form-urlencoded" media type.

**Comment by peterfronc** [comment]
Yes, correct. What happens is that when "application/x-www-form-urlencoded" is set on header, the form values are null. If in my page client I set header to "plain/text" the values are set.
So it should be that default is the forms reading applied (url-encoded). 
Any news on when the release will be updated?

**Comment by thboileau** [comment]
Sorry, I mean - using the sample application I've sent to you plus the future 2.3.3 - the Jaxrs client request sent is correct, and the Jaxrs server correctly understands the response.
I think the 2.3.3 will be fine on monday.

**Comment by peterfronc** [comment]
Thanks a lot, Ill try it on Monday.

**Comment by peterfronc** [comment]
Seems to be fixed with recent updates. There is another thing but it may be worth another note.
When you use filter and access request parameters, the parameters are consumed, however after passing to chain same request, the form parameters are nulls (It may be the case that restlet operates on the consumed stream to read parameters).

**Comment by thboileau** [comment]
Hi @peterfronc, I've opened issue #1120 for that point.
I close this one.
