### ISSUE TITLE
Missing support for Access-Control-Max-Age (CORS header)

### ISSUE THREAD

**Issue by tliron** [restlet/restlet-framework-java#1109]
The API should probably be Response.setAccessControlMaxAge.

It would also be nice if the CorsFilter and CorsService supported this.

**Comment by demsey2** [comment]
+1

**Comment by thboileau** [comment]
thanks @tliron and @demsey2 . It will be part of 2.3.8.

**Comment by ds-perfit** [comment]
Hi @thboileau! any plans on releasing 2.3.8 with this feature soon?

**Comment by thboileau** [comment]
Hello @ds-perfit 
I've created the tag, if everything is ok, it will be released in a few hours.
