### ISSUE TITLE
LOCK and UNLOCK methods are NOT safe

### ISSUE THREAD

**Issue by zsoltszloboda** [restlet/restlet-framework-java#1112]
org.restlet.data.Method defined LOCK and UNLOCK methods as safe; however they are not safe, according to the WevDav RFC: http://www.webdav.org/specs/rfc4918.html
(Restlet version: 2.3.1 GAE)

**Comment by thboileau** [comment]
hi @zsoltszloboda, thanks for reporting this, you're totally right.

**Comment by thboileau** [comment]
fixed in 2.3 branch (future 2.3.4).
