### ISSUE TITLE
Restlet on jdk 1.6, its possible?

### ISSUE THREAD

**Issue by danipenaperez** [restlet/restlet-framework-java#1116]
Hi all, 
I´m triying to run restlet on a JVMEmbebed which has restricctions from Jre 1.6.

java.lang.UnsupportedClassVersionError: org/restlet/Restlet : Unsupported major.minor version 51.0

Any suggest?

Thanks in advance!

**Comment by thboileau** [comment]
Hello @danipenaperez,

unfortunately, the current stable release 2.3 is available on JDK7 only (cf http://restlet.com/technical-resources/restlet-framework/guide/2.3/introduction/whats-new/2.3).
You can use any release before if you want.

**Comment by amilabanuka** [comment]
is there any lower version that the latest build that will work on jdk 1.6?

**Comment by jlouvel** [comment]
RF version 2.3 works with JDK 1.6.
http://restlet.com/technical-resources/restlet-framework/guide/2.3/introduction/whats-new/2.2

You can download it in this section:
http://restlet.com/downloads/past/
