### ISSUE TITLE
Setting a custom Content-Range Header in Restlet for use in Dojo pagination fails

### ISSUE THREAD

**Issue by thboileau** [restlet/restlet-framework-java#1132]
cf [StackOverFlow question](http://stackoverflow.com/questions/32047984/setting-a-custom-content-range-header-in-restlet-for-use-in-dojo-pagination-fail):

**Comment by thboileau** [comment]
cf PR: #1134

**Comment by mgcenit** [comment]
Still waiting for this fix.

**Comment by thboileau** [comment]
thanks for the heads up.
Do you need a version asap?
