### ISSUE TITLE
Two road map version pages

### ISSUE THREAD

**Issue by monishappusamy** [restlet/restlet-framework-java#1135]
I was trying to contribute and I found two roadmap pages for version 3

One at,
https://github.com/restlet/restlet-framework-java/wiki/Road-map-of-version-3.0

Another at,
https://github.com/restlet/restlet-framework-java/wiki/Road-map-of-version-3

I suppose the latter one is the latest, we can delete the first page.

**Comment by thboileau** [comment]
Hello,

thanks a lot for reporting this issue, I've deleted the first page wich
were, as you said, less up to date.

Best regards,
Thierry Boileau

2015-08-24 5:42 GMT+02:00 monish appusamy <notifications@github.com>:

> There are two roadmap pages for version 3.0
>
> One at,
>
> https://github.com/restlet/restlet-framework-java/wiki/Road-map-of-version-3.0
>
> Another at,
>
> https://github.com/restlet/restlet-framework-java/wiki/Road-map-of-version-3
>
> I suppose the latter one is the latest, we can delete the first page.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/restlet/restlet-framework-java/issues/1135>.
>



-- 
*Thierry Boileau, Mr B*
+1 (408) 387-3184 • tboileau@restlet.com

<http://restlet.com/>
6 Rue Rose Dieng-Kuntz • Nantes, 44300 • France
