### ISSUE TITLE
No GAE version for org.restlet.ext.guice

### ISSUE THREAD

**Issue by rcbeuker** [restlet/restlet-framework-java#1136]
Why isn't there a GAE version for org.restlet.ext.guice?
For now, can i just take the JEE version?

http://restlet.com/technical-resources/restlet-framework/guide/2.3/extensions/editions-matrix

**Comment by jlouvel** [comment]
Please try the JEE version and let us know if it works fine to be could include it in the GAE edition.

**Comment by rcbeuker** [comment]
Hello Jerome,

Yes, the JEE version works an can be included in the GAE edition.

Met vriendelijke groet,

Roland Beuker
*Arcus Solutions*
*06-33974573*

**Comment by thboileau** [comment]
Hi @rcbeuker , thanks a lot for the test.
It is now part of 2.3 branch (will be part of 2.3.5 release, coming soon).
