### ISSUE TITLE
ResourceException constructor calling incorrect Status constructor

### ISSUE THREAD

**Issue by cgatesman** [restlet/restlet-framework-java#1139]
It seems to me that this ResourceException constructor:

```java
    public ResourceException(Status status, String description, Throwable cause) {
        this(new Status(status, cause, description), cause);
    }
```

should actually be calling `new Status(status, cause, null, description)`.  Currently, it is incorrectly passing a description as a reasonPhrase.  This, in turn, causes IllegalArgumentExceptions from `Status.checkReasonPhrase()` when you catch a Throwable in your Resource and attempt to use this constructor to throw a ResourceException.

**Comment by thboileau** [comment]
Thanks @cgatesman , the fix is now part of the 2.3 branch.
