### ISSUE TITLE
NPE while setting CORS headers

### ISSUE THREAD

**Issue by ralphvanetten** [restlet/restlet-framework-java#1145]
If you use `setAccessControlExposeHeaders()` or any of the other methods for settings CORS headers on the `Response` class you'll get an NPE.

This is caused by calling `this.accessControlExposeHeaders.clear();` in line https://github.com/restlet/restlet-framework-java/blob/2.3.4/modules/org.restlet/src/org/restlet/Response.java#L768
`this.accessControlExposeHeaders` is never initialized with a real object and `null` until you call `getAccessControlExposeHeaders`.

I've tested it with restlet 2.3.4

**Comment by jlouvel** [comment]
@ralphvanetten Thanks for spotting this! Do you think you can contribute a PR? Otherwise, @thboileau  will take care of this as soon as possible.

**Comment by thboileau** [comment]
Hi @ralphvanetten , I'm not able to reproduce this NPE.
Is it still accurate, do you have any sample code?

**Comment by ralphvanetten** [comment]
Added a test case in pull request #1149

**Comment by thboileau** [comment]
Thanks @ralphvanetten , I've fixed the issue, and added your regression test case.
I wonder what I've tested...

**Comment by thboileau** [comment]
NB: we will release 2.3.5 very soon.

**Comment by ralphvanetten** [comment]
great, thanks
