### ISSUE TITLE
setAccessControlExposeHeaders is broken

### ISSUE THREAD

**Issue by bwatsonluke** [restlet/restlet-framework-java#1150]
Response.setAccessControlExposeHeaders is broken in version 2.3.4.  Calling it results in a NullPointerException.
The fault is line 766 of setAccessControlExposeHeaders which synchronises on getAccessControlAllowHeaders() instead of getAccessControlExposeHeaders().

**Comment by thboileau** [comment]
Hi @bwatsonluke , thanks for reporting this issue.
this has been [fixed](https://github.com/restlet/restlet-framework-java/issues/1145)

**Comment by thboileau** [comment]
The fix will be part of the 2.3.5 release.

**Comment by bwatsonluke** [comment]
Hi @thboileau .  This is working fine for me with 2.3.5 .  Thanks!
