### ISSUE TITLE
HeaderUtils.addResponseHeaders doesn't add header for HEADER_ACCESS_CONTROL_EXPOSE_HEADERS

### ISSUE THREAD

**Issue by bwatsonluke** [restlet/restlet-framework-java#1151]
The Access-Control-Expose-Headers header is not handled properly in HeaderUtils.  In particular,
copyResponseTransportHeaders has code for handling HEADER_ACCESS_CONTROL_EXPOSE_HEADERS but addResponseHeaders does not.  Consequently, even if the header has been set on the Response it is not being set on the HttpResponse.

**Comment by thboileau** [comment]
Hi @bwatsonluke, I've tried the current branch 2.3, and I don't notice this point.
I've even tried, and it worked for me.
Which version of the framework are you using?

**Comment by bwatsonluke** [comment]
I was trying with 2.3.4.  After working around #1150 (by calling getAccessControlExposeHeaders() once before calling setAccessControlExposeHeaders()) I was setting "ETag" as an exposed header.  However, in the browser, the ETag wasn't visible and looking at the HTTP response I found that Access-Control-Expose-Headers was not present in the web server responses.  I put it down to the lack of an appropriate call in HeaderUtils.addResponseHeaders.  Looking at what I think is still current (https://github.com/restlet/restlet-framework-java/blob/master/modules/org.restlet/src/org/restlet/engine/header/HeaderUtils.java) I don't see anything to set the HttpResponse header for the Access-Control-Expose-Headers header .  I'd expect to see something like the same code as for the Access-Control-Allow-Headers header.

**Comment by thboileau** [comment]
Hi @bwatsonluke , I see: I've have not copied the updates made on branch `2.3` to branch `master`.
Could you try with the code of branch 2.3?

**Comment by bwatsonluke** [comment]
Hi @thboileau , I'm away from work at the moment so it is hard for me to retry. I will when I get back.  But I have looked at your recent change in the 2.3 branch and I am sure that it resolves the issue I'd found.  Thanks.

**Comment by bwatsonluke** [comment]
Hi @thboileau .  This is working fine for me with 2.3.5 .  Thanks!
