### ISSUE TITLE
Using HTTP_OAUTH_BEARER with raw value add a trace: "Challenge scheme HTTP_Bearer not supported by the Restlet engine."

### ISSUE THREAD

**Issue by thboileau** [restlet/restlet-framework-java#1152]
The request is well sent, but a log trace with level warning.

**Comment by koscejev** [comment]
This is still happening in `org.restlet.engine.security.AuthenticatorUtils#parseResponse` and `#parseRequest` where it's not checked whether raw value is used in `ChallengeResponse` before complaining that there's no matching `AuthenticatorHelper` defined.
