### ISSUE TITLE
StatusService.toStatus() is not called

### ISSUE THREAD

**Issue by adolski** [restlet/restlet-framework-java#1156]
I've observed this in Restlet JSE 2.3.4 and 2.3.5. I have a custom status service that extends StatusService:

```java
    private class CustomStatusService extends StatusService {

        @Override
        public Representation toRepresentation(Status status, Request request,
                                               Response response) {
            ...
        }

        @Override
        public Status getStatus(Throwable t, Request request, Response response) {
            ...
        }

    }
```

I set it in my Application constructor:

```java
    this.setStatusService(new CustomStatusService());
```

It works perfectly, except that `getStatus()` is deprecated; the docs say to use `toStatus()` instead. But when I do that, `toStatus()` is never called.

**Comment by thboileau** [comment]
Hi @adolski , thanks for reporting this issue.

As a workaround, could you override also the `toStatus(Throwable throwable, Resource resource)` method, for example as follow:

```java
return toStatus(throwable,
                (resource == null) ? null : resource.getRequest(),
                (resource == null) ? null : resource.getResponse());
```
