### ISSUE TITLE
Bug in documentation

### ISSUE THREAD

**Issue by adolski** [restlet/restlet-framework-java#1157]
On this page: http://restlet.com/technical-resources/restlet-framework/guide/2.3/editions/jse/logging

There is a paragraph that says, "If the logger name you are looking for isn't listed, there is an easy way to detect it. You just have to call the static "org.restlet.engine.log.TraceHandler.register()" method at the beginning of your program."

But, org.restlet.engine.log.TraceHandler does not exist in 2.3.5.

**Comment by jlouvel** [comment]
This class present in v2.0:
https://github.com/restlet/restlet-framework-java/blob/2.0/modules/org.restlet/src/org/restlet/engine/log/TraceHandler.java

was removed in v2.1 in favor on the configurable JDK's ConsoleHandler class:
http://docs.oracle.com/javase/6/docs/api/java/util/logging/ConsoleHandler.html

which can achieve the same result (even though more tricky to configure)...

**Comment by adolski** [comment]
@jlouvel Thanks!
