### ISSUE TITLE
Abstract method UriBuilder#uri(String uriTemplate) is not implemented

### ISSUE THREAD

**Issue by tmortagne** [restlet/restlet-framework-java#1158]
Among other things JAX-RS introduced a new UriBuilder#uri(String uriTemplate) method. In the Maven package org.restlet.ext.jaxrs-2.3.5 indicate that it implements javax.ws.rs-api-2.0 (by the way there is a 2.0.1 now) but this method is not implemented anywhere (I checked AbstractUriBuilder, ExtendedUriBuilder and UriBuilderImpl) leading to

``` java
    java.lang.AbstractMethodError: javax.ws.rs.core.UriBuilder.uri(Ljava/lang/String;)Ljavax/ws/rs/core/UriBuilder;
        at javax.ws.rs.core.UriBuilder.fromUri(UriBuilder.java:119)
        ...
```

I don't understand how this module could even build unless it's using JAX-RS 1.0 API at build time.

**Comment by jlouvel** [comment]
Sorry for the confusion, but the JAX-RS extension is still only supporting v1.0 of JAX-RS.
We have a plan to upgrade to JAX-RS 2.0 by embedding RESTeasy in Restlet Framework v3.0.
https://github.com/restlet/restlet-framework-java/wiki/Road-map-of-version-3

**Comment by tmortagne** [comment]
> the JAX-RS extension is still only supporting v1.0 of JAX-RS

In that case the Maven package dependencies should really be fixed.

**Comment by jlouvel** [comment]
I agree, @thboileau can you take care of that?

**Comment by jlouvel** [comment]
Closing as we are removing JAX-RS in branch 2.5
