### ISSUE TITLE
Encoding issue when using CookieAuthenticator

### ISSUE THREAD

**Issue by templth** [restlet/restlet-framework-java#1159]
Arjohn Kampman found out a problem with encoding when trying to login using the CookieAuthenticator.

When the default encoding is latin1 and we want to use for example chinese characters, the latters won't be correctly decoded. The consequence here is that following calls won't be allowed...

See Arjohn's message of the mailling list:

> We just ran into an issue with CookieAuthenticator not supporting various Unicode names and 
> passwords. We have debugged the issue to the encrypt() and decrypt() methods in CryptoUtils. These 
> methods converts byte[] to String and back again using the platform's default character encoding. If 
> that default encoding is ISO-8859-1, for example, decoding a cyrillic or Chinese character will result in 
> '?' characters in the resulting byte array.
> 
> A simple solution is to always use UTF-8 for the conversion:
> 1) replace calls to String.getBytes() with String.getBytes(StandardCharsets.UTF_8)
> 2) replace calls to constructor String(byte[]) with String(byte[], StandardCharsets.UTF_8)

**Comment by thboileau** [comment]
will be part of 2.3.8.
