### ISSUE TITLE
Bad log level when using `ChallengeScheme.HTTP_ OAUTH_BEARER` in a `ClientResource`

### ISSUE THREAD

**Issue by boillodmanuel** [restlet/restlet-framework-java#1161]
When using `ChallengeScheme.HTTP_ OAUTH_BEARER` in a `ClientResource`, the client call works  but log a warning message that seems to indicate that this scheme is not supported:

Log:
```shell
WARNING: Challenge scheme HTTP_Bearer not supported by the Restlet engine.
```

Code:
```java
import org.restlet.data.ChallengeResponse;
import org.restlet.data.ChallengeScheme;
import org.restlet.resource.ClientResource;

public class Test {

    public static void main(String[] args) {
        ClientResource clientResource = new ClientResource("http://localhost:9000");
        ChallengeResponse challengeResponse = new ChallengeResponse(ChallengeScheme.HTTP_OAUTH_BEARER);
        challengeResponse.setRawValue("__bearer_token_value__");
        clientResource.setChallengeResponse(challengeResponse);
        clientResource.get();
    }
}
```

HTTP Request headers received is correct

```shell
GET / HTTP/1.1
Date: Wed, 21 Oct 2015 08:47:51 GMT
Accept: */*
User-Agent: Restlet-Framework/3.17.4
Authorization: Bearer __bearer_token_value__
Cache-Control: no-cache
Pragma: no-cache
Host: localhost:9000
Connection: keep-alive
```

I suggest to update the message and the log level to something like (class `AuthenticatorUtils`):
```java
FINE(ST): Challenge scheme HTTP_Bearer do not update the reference.
```

**Comment by jlouvel** [comment]
Looking at AuthenticatorUtils.formatResponse() this warning shouldn't be displayed if you set a raw value manually.
https://github.com/restlet/restlet-framework-java/blob/master/modules/org.restlet/src/org/restlet/engine/security/AuthenticatorUtils.java#L242

Isn't this warning coming from the HTTP response received instead?

**Comment by thboileau** [comment]
@boillodmanuel , I confirm I don't see any warning message using RF 2.3.

**Comment by thboileau** [comment]
I think this is related to this issue: https://github.com/restlet/restlet-framework-java/issues/1152
The fix has been shipped with release 2.3.5.

**Comment by boillodmanuel** [comment]
Version 2.3.5 fixes this issue. You can close it

**Comment by thboileau** [comment]
thanks @boillodmanuel !
