### ISSUE TITLE
ConvertRepresentationExceptions can't be handled by Jaxrs ExceptionMapper

### ISSUE THREAD

**Issue by templth** [restlet/restlet-framework-java#1162]
From the StackOverflow question http://stackoverflow.com/questions/33438562/what-handled-the-convert-exception.

**Comment by gartcimore** [comment]
one of my team mate worked on that, and found the following : 
>This error is an issue linked to java jaxrs.
>Two librairies of jaxrs were shipped (1.1 and 2.0) leading to a runtime error >(java.lang.AbstractMethodError).
>
>jsr311-api-1.1.1.jar
>javax.ws.rs-api-2.0.jar
>Only jar jsr311-api-1.1.1.jar should be used, as there are some incompatibilities between jaxrs 2.0 and 1.1

**Comment by jlouvel** [comment]
Closing as we are removing JAX-RS in branch 2.5
