### ISSUE TITLE
Problem with case sensitivity of query parameters wit JAX-RS

### ISSUE THREAD

**Issue by templth** [restlet/restlet-framework-java#1163]
See this question on the Restlet Google group: https://groups.google.com/a/restlet.org/forum/#!topic/framework-discuss/3F50zZybGcI.

Query parameters should handle case sensitivity for names:

* Within `@QueryParam` annotation (it's the case)
* From `@Context` annotation and `UriInfo` class (it's not the case)

**Comment by gartcimore** [comment]
Hello Thierry,
I tried to fix this issue. This is my first contribution to a github project, so tell me if I'm not doing thing "the right way".
Also about the fix, this is very simple, if you have something else to suggest, I'm all ears
