### ISSUE TITLE
StringIndexOutOfBoundsException in HeaderReader when reading header with empty value

### ISSUE THREAD

**Issue by TimurGasrataliev** [restlet/restlet-framework-java#1167]
org.restlet.engine.header.HeaderReader#readHeader(java.lang.CharSequence) is throwing StringIndexOutOfBoundsException when processing empty-valued headers

Test case:
```java
import org.junit.Assert;
import org.restlet.data.Header;
import org.restlet.engine.header.HeaderReader;
import org.restlet.test.RestletTestCase;
import java.io.IOException;

public class HeaderReaderTestCase extends RestletTestCase {
    public void testRreadHeaderEmptyValue() throws IOException {
        Header result = HeaderReader.readHeader("My-Header: ");
        Assert.assertNotNull(result);
        Assert.assertEquals("My-Header", result.getName());
        Assert.assertNull(result.getValue());
    }
}
```
I was able to reproduce this issue in master and 2.3 branches

**Comment by thboileau** [comment]
thanks @TimurGasrataliev !
I think there is another issue in this class: the HTTP spec allows this kind of header line:
```
field-name:
```
which is not supported by the framework.
Here is a link to the specification: https://tools.ietf.org/html/rfc7230#page-22

What do you think @jlouvel ?

**Comment by thboileau** [comment]
fixed by this commit https://github.com/restlet/restlet-framework-java/commit/9758ab331e484dc1dfc42b92af46345c56feb9e8

**Comment by thboileau** [comment]
will be part of 2.3.6
