### ISSUE TITLE
JaxRS exceptions handling, missing thrown exception objects.

### ISSUE THREAD

**Issue by theprivateland** [restlet/restlet-framework-java#1173]
I have a problem, I use jaxrs implementation of restlet and have added default status service to be able to catch uncaught exceptions and save stack trace information.

It is important issue as being unable to save errors is a severe issue.

I have status service class:

``` java

public class DefaultStatusHandler extends StatusService {

  private static final Log log = new Log(DefaultStatusHandler.class);

  public DefaultStatusHandler() {
    super();
    this.setEnabled(true);
    this.setOverwriting(false);
  }

  @Override
  public Status toStatus(Throwable t, Request request, Response response) {
    Status status = super.toStatus(t, request, response);
    return status;
  }

  @Override
  public Representation toRepresentation(
          Status status,
          Request request,
          Response response) {
    Throwable t = status.getThrowable();

    if(status.isError()) {
      log.severe("Unexpected service exception.", t, true);

      if (t != null) {
        PrintWriter pw = new PrintWriter(new StringWriter());
        t.printStackTrace(pw);
        log.severe("Stack trace:\n" + pw.toString());
      }
    }

    return super.toRepresentation(status, request, response);
  }
}

```

Its added:

``` java

public class JaxRsApp extends JaxRsApplication {

  static Log log = new Log(JaxRsApp.class);

  public JaxRsApp () {
    super();
    RestServiceApp app = new RestServiceApp();
    this.add(app);
    this.setStatusService(new DefaultStatusHandler());
  }
}

```

in one of jaxrs services I run:

``` java
if (true) {
        throw new SQLException("catch me!");
      }
```

Any of `toStatus` methods is not being entered and `toRepresenations` is being entered but the throwable is null!

I need help here - is this correct? Where is the exception? Why `toStatus` is not entered?

**Comment by theprivateland** [comment]
Anyone? It should be very easy to reproduce.

The app is deployed in tomcat env.

**Comment by gartcimore** [comment]
Did you checked if this is similar to issue https://github.com/restlet/restlet-framework-java/issues/1162 ?

**Comment by peterfronc** [comment]
Doesn't look like. I use plain jax-rs setup, I didnt define any exception mappings, its just about plain exceptions handling - the status service that handles exceptions receives one but exception object is null.
Its simple case - the exception object should be present, however status.getThrowable() is null.

**Comment by theprivateland** [comment]
Anyone? Its a real problem, I can use in roduction system that exceptions cant be logged - this will force me to roll back to jersey stuff and i really dont like jersey one.

**Comment by theprivateland** [comment]
Anyone?

**Comment by theprivateland** [comment]
Anyone?

**Comment by theprivateland** [comment]
@gartcimore ?

**Comment by gartcimore** [comment]
I didn't take a look at your problem, so I don't have a solution for you

**Comment by theprivateland** [comment]
Hmm, anyone then? It should be fairly simple to check where exception is swallowed.

**Comment by peterfronc** [comment]
Guys, anyone ?

**Comment by theprivateland** [comment]
I have used the mapper finally but the exception should be passed to status anyway. Ill close this issue as noone responds.

**Comment by jlouvel** [comment]
Sorry for the delay, let's keep this issue open as we'll eventually need to fix it.
The StatusService has been designed to work with regular Restlet Application especially relying on ServerResource, which isn't the case of JaxRsApplication subclasses which work differently. However, it should be possible to bridge StatusService and JaxRsApplication.

**Comment by hehsiao** [comment]
Is there any workaround or fixes for this issue?

**Comment by jlouvel** [comment]
@hehsiao One user has used a custom mapper to workaround the issue. It would be good to have someone contribute a fix.

**Comment by jlouvel** [comment]
Closing as we are removing JAX-RS in branch 2.5
