### ISSUE TITLE
Future of the SDC extension / connector

### ISSUE THREAD

**Issue by ssrini** [restlet/restlet-framework-java#1177]
Google pulled the SDC connector quite some time back.  However the connector itself works remarkably well and the code was available on google code.

Now with google code sunset (https://code.google.com/p/google-secure-data-connector/), it would be a good idea I guess for the Restlet team to export this to Github?  Since the SDC extension still works, it would be good to also protect the SDC connector (client).

**Comment by jlouvel** [comment]
Great idea! We need to step up and take a lead on that to ensure continuous SDC technology availability. Let me discuss this with the rest of my team.

**Comment by ssrini** [comment]
Thats great.  Please let me know if we can also pitch in to help if any.

**Comment by jlouvel** [comment]
Closing as we removed SDC extension previously
