### ISSUE TITLE
Replacement for ClientStore/ClientStoreFactory

### ISSUE THREAD

**Issue by talmdal** [restlet/restlet-framework-java#1186]
I am working with an application that uses the 2.2-M3 release, I know it's old and a milestone release :-( but ... you have to play the cards your dealt. Our application uses the ClientStore/ClientStoreFactory for storing client information.  Somewhere between 2.2-M3 and 2.2.0 these classes disappeared.

Could someone tell me where they were moved to **or** what they were replaced with.

Thanks
Tim

**Comment by thboileau** [comment]
Hi @talmdal , these two classes have been replaced by 
* ClientManager interface (with its shipped implementations AbstractClientManager and MemoryClientManager)
* and org.restlet.ext.oauth.internal.Client interface (and its shipped implementation MemoryClient)

I try to give some more details about how to use them.

**Comment by talmdal** [comment]
Thanks for the response, that gives me a good start now that I know what I'm looking for, but any addition details would helpful.

Thanks again
Tim

**Comment by talmdal** [comment]
@thboileau,  just wondering if you had a chance to find some more details about how to use them.  If not, I can probably find some examples in your code. 

Thanks
Tim

**Comment by thboileau** [comment]
Hello, @talmdal I have some time now and I'm having a look.
There are sample code in the `org.restlet.test` module, package `org.restlet.test.ext.oauth`.

**Comment by talmdal** [comment]
Hi Thiery

Thanks for pointing out some sample code.

We have implemented an Oauth server using the older milestone version.  It's time to upgrade and just needed to know what to replace the client store with.

I appreciate your offer of translating some code, but I'm in a sensitive environment which makes sharing code difficult.

Thanks again, you saved me a lot of leg work finding where to look and I appreciate that.  I'll close this issue and I'll open another one if I hit "any  bumps in the road".
