### ISSUE TITLE
is there any solution for ip address binding?

### ISSUE THREAD

**Issue by swiminger** [restlet/restlet-framework-java#1197]
I met a problem, Restlet server has to change the network from eth0 to wifi, I have not find the way to let the component to change the ip address.  Does anyone can help?

**Comment by thboileau** [comment]
Hi @swiminger , I'm not clearly sure to understand your question.
If you want to bind your server to a specific IP address, you can use a [virtual host](https://restlet.com/technical-resources/restlet-framework/javadocs/2.3/jse/api/org/restlet/routing/VirtualHost.html).

Let's say that your current code is based on the component's default host:
```java
component.getDefaultHost().attach("/myapp", application);
```

You can define your own virtual host and filter requests based on the server address:
```java
VirtualHost vHost = new VirtualHost(component.getContext());
vHost.setServerAddress("127.0.0.1"); // the IP address you want to "listen to".
vHost.attach("/myapp", application);

component.getHosts().add(vHost);
```

**Comment by swiminger** [comment]
Got it. thanks for your help.
