### ISSUE TITLE
JAXRS API do not support uri with "?"  character?

### ISSUE THREAD

**Issue by ShawnLye** [restlet/restlet-framework-java#1213]
Hi,
 I found org.restlet.ext.jaxrs.internal.util.RemainingPath will remove all the characters after "?" in a uri. Are there any suggestions about getting the "key=value" parameters after the "?" from url like "http://localhost/student?id=124&name=Sam"?

**Comment by igorbakman** [comment]
try this:
`Form frm = request.getResourceRef().getQueryAsForm();`
later you can:
`frm.getFirst(parameter).getValue();`

**Comment by ShawnLye** [comment]
@igorbakman 
Hi,
I mean I want to get the parameters in the method of resources, For url "http://localhost/student/query?id=124&name=Sam", like:
`@Path("student")
public StudentResource {
       @Get
       @Path("query?id={id}&name={name}")
       public String queryStudent(@PathParam("id") String id, @PathParam("name") String name) {
              studentDao.query(id, name);
              ......
       }
}`

**Comment by jlouvel** [comment]
Closing as we are removing JAX-RS extension in version 2.5
