### ISSUE TITLE
Document request body for swagger

### ISSUE THREAD

**Issue by ratretola** [restlet/restlet-framework-java#1239]
How does one document a Post request's body parameter for swagger? All of my post requests accept Representation objects which are not typed so the swagger UI simply shows a text box. If I temporarily change my method to accept a custom object, it does get introspected properly and shows in the swagger ui.

This is the last piece of the puzzle for me. I have tried using the @ApiParam but don't see any output from this. It also doesn't allow for actually typing the request object to show that my service requires my specific request object.

Here is my resource interface:

@Api(value = "address", description = "mailing address services")
public interface AddressValidateInterface {

```
@Post
@Path("/address/validate/") 
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
@ApiOperation(value = "validates mailing addresses *", tags = "address", consumes="application/json", 
produces="application/json")
@ApiResponses({
    @ApiResponse(code = 200, message = "Address validation successful", response=AddressResult.class),
    @ApiResponse(code = 400, message = "Invalid or missing data in request", response=Result.class),
    @ApiResponse(code = 401, message = "Unauthorized", response=StatusInfo.class)
})    
public Representation validate(@ApiParam(name="body", value = "Address to be validated", required = true, defaultValue="test") Representation entity);
```

}

Below is the output within swagger UI:

<img width="1017" alt="screen shot 2016-09-30 at 1 19 32 pm" src="https://cloud.githubusercontent.com/assets/1675740/19000438/98eaa3fe-8710-11e6-8393-bf4ff023a17b.png">

What I would actually want is this showing the request (I forced this by changing my method definition to public Representation validate(AddressRequest entity);):
<img width="990" alt="screen shot 2016-09-30 at 1 21 50 pm" src="https://cloud.githubusercontent.com/assets/1675740/19000500/ec0114d8-8710-11e6-8975-b7ecb7bbb7bf.png">

**Comment by jlouvel** [comment]
Closing as we are removing JAX-RS extension in version 2.5
