### ISSUE TITLE
default http server closes connection after a 204

### ISSUE THREAD

**Issue by slintes** [restlet/restlet-framework-java#1244]
Hi,

I came across a strange behaviour of the default Restlet HTTP server: when a response is just a status 204 without content, the connection is closed without announcing it with a "Connection: close" HTTP header. This confuses at least the Apache HTTP client, which doesn't check if the connection is still open, at least when the next request is executed quite fast after the 204 request. 

I have 2 questions about this:
- Why does Restlet close the connection at all?
- Why does it not set the "Connection: Close" header?

Example code:
```
	    router.attach("/empty", new Restlet() {
	    	@Override
	    	public void handle(Request request, Response response) {
	    		response.setStatus(Status.SUCCESS_NO_CONTENT);
	    	}
		});
```

Server log:
```
Oct 31, 2016 10:45:06 AM org.restlet.routing.TemplateRoute beforeHandle
FINER: Delegating the call to the target Restlet
Oct 31, 2016 10:45:06 AM org.restlet.engine.log.LogFilter afterHandle
INFO: 2016-10-31	10:45:06	127.0.0.1	-	-	9090	GET	/app/empty	-	204	0	0	5	http://localhost:9090	Apache-HttpClient/4.5.2 (Java/1.8.0_66)	-
Oct 31, 2016 10:45:06 AM sun.net.httpserver.ServerImpl logReply
FINE: GET /app/empty HTTP/1.1 [204  No Content] ()
Oct 31, 2016 10:45:06 AM sun.net.httpserver.HttpConnection close
FINEST: Closing connection: java.nio.channels.SocketChannel[connected local=/127.0.0.1:9090 remote=/127.0.0.1:61456]
```

I also reported this to the Apache HTTP team... they say that this is at least strange behaviour of the server, while not strictly forbidden. See this mailing list thread: http://mail-archives.apache.org/mod_mbox/hc-httpclient-users/201610.mbox/%3CetPan.58108d0c.7bea6c4a.dde5@slintes.net%3E

Other HTTP clients (I tested Vertx and OkHttp) doesn't have this problem. But I still think that this could be handled nicer on server side.
When I use the Jetty extension, I also don't see this problem.

Find example code at https://github.com/slintes/httpclienttest with 4
components:

- the Restlet server with 2 endpoints, “test” which returns a 200 with response
body, and “empty” which returns a 204 without body
- an Apache HttpClient based test client, which request “test”, “empty”, “test”,
“test”: the 3rd request fails, unless you increase the sleep in line 35. The 4th
request is always successful.
- for comparison a Vertx and a OkHttp based test client, which do the same and
always succeed.

Greetings,

Marc

**Comment by jlouvel** [comment]
Hi Marc, the default HTTP server is based on com.sun.net.httpserver package. It isn't very advanced and I wouldn't recommend it for production loads. Using Jetty extension is probably the best way to solve your issue.

**Comment by slintes** [comment]
Ok, thanks!
I came across this issue while doing tests with JMeter, which uses the Apache Http Client (at least per default). In our product we use another client, which can handle the problem. But we will consider using the Jetty extension nevertheless.
