### ISSUE TITLE
DHC 1.3.5 -- history is not working

### ISSUE THREAD

**Issue by shapiro2** [restlet/restlet-framework-java#1247]
Looks like DHC got updated today (version 1.3.5) and the history sidebar is not functional.
The history is listed, but clicking on any url listed does *not* put the url/params/etc into the main panel

**Comment by jplegoff** [comment]
Hi Michael,

We have just released a fix version (version 1.3.5.1).

Can you confirm us this solves the issue on your side?

Thanks for your comprehension.

**Comment by shapiro2** [comment]
Yes, it seems to have fixed the problem. Thank you for the rapid response!

________________________________
