### ISSUE TITLE
EmptyRepresentation entity for 204 response causes the client to hang 

### ISSUE THREAD

**Issue by fatemehb12** [restlet/restlet-framework-java#1253]
For a 204 (No Content) response, the JaxRsRestlet returns an EmptyRepresentation entity (instead of a null entity). This causes a cURL client to hang indefinitely, as it waits for further output. Returning a null entity fixes the issue.

**Comment by thboileau** [comment]
Hi @fatemehb12,
thanks for reporting this issue.
Do you have any simple test case?
Can you send us the headers returned by the server?

**Comment by fatemehb12** [comment]
Hi Thierry,

Sorry for the late response on this. I have attached a sample script that we executed (which requires that you have a local Unisphere for VMAX server running). The output is as follows:
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): localhost
send: b'DELETE /univmax/restapi/sloprovisioning/symmetrix/000197800128/storagegroup/FATEMEH_SG HTTP/1.1\r\nHost: localhost:84
43\r\nAccept: */*\r\nConnection: keep-alive\r\nAccept-Encoding: gzip, deflate\r\nUser-Agent: python-requests/2.12.3\r\nConten
t-Length: 0\r\nAuthorization: Basic c21jOnNtYw==\r\n\r\n'
reply: 'HTTP/1.1 204 No Content\r\n'
DEBUG:requests.packages.urllib3.connectionpool:https://localhost:8443 "DELETE /univmax/restapi/sloprovisioning/symmetrix/0001
97800128/storagegroup/FATEMEH_SG HTTP/1.1" 204 0

It just hangs on the last line and does not return to the command prompt.

Here is the output when the stream option is set to true:
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): localhost
send: b'DELETE /univmax/restapi/sloprovisioning/symmetrix/000197800128/storagegroup/FATEMEH_SG HTTP/1.1\r\nHost: localhost:84
43\r\nAccept-Encoding: gzip, deflate\r\nConnection: keep-alive\r\nUser-Agent: python-requests/2.12.3\r\nAccept: */*\r\nConten
t-Length: 0\r\nAuthorization: Basic c21jOnNtYw==\r\n\r\n'
reply: 'HTTP/1.1 204 No Content\r\n'
DEBUG:requests.packages.urllib3.connectionpool:https://localhost:8443 "DELETE /univmax/restapi/sloprovisioning/symmetrix/0001
97800128/storagegroup/FATEMEH_SG HTTP/1.1" 204 0
header: Connection header: Set-Cookie header: Server header: Transfer-Encoding header: Content-Type header: U4V-SHARDPROXY-TIME header: Accept-Ranges header: Date <Response [204]>

In that case it works, but if we run the command using curl (which doesn’t have the stream option), it hangs and does not return to the command prompt.

Thanks,

-Fatemeh

**Comment by jlouvel** [comment]
Closing as we are removing JAX-RS in branch 2.5
