### ISSUE TITLE
Maven metadata out-of-date

### ISSUE THREAD

**Issue by pyxide** [restlet/restlet-framework-java#1255]
Hello,

the file http://maven.restlet.com/org/restlet/jse/org.restlet/maven-metadata.xml has not been updated since  2016-03-15 and does not list the last releases.
Could you please update it ?

**Comment by thboileau** [comment]
Hello @pyxide 
the repository has been updated. Could you confirm that it has been fixed?

thanks for reporting this issue.

**Comment by pyxide** [comment]
It's OK for me, Thank you.
