### ISSUE TITLE
Address is ignored when creating a HttpServer

### ISSUE THREAD

**Issue by bquintanaj** [restlet/restlet-framework-java#1256]
When creating an InetSocketAddress in HttpServerHelper, right now only the port is taken into account. If a hostname was provided in  RestletHelper, it's not used. So at the end, such InetSocketAddress is always listening at 0.0.0.

Listening at a specific address is useful f.e. when the loopback interface is required for security reasons.

**Comment by bquintanaj** [comment]
I've created a pull request for it here:
https://github.com/restlet/restlet-framework-java/pull/1257

Can anyone please have a look and give me some feedback? (or approve if it's ok :) )
Thank you.

**Comment by thboileau** [comment]
By the way, thanks for posting this issue!
