### ISSUE TITLE
org.restlet.engine.util.CallResolver not resolving variables h* and f*

### ISSUE THREAD

**Issue by PSpSynedra** [restlet/restlet-framework-java#1260]
Starting with commit a72a92455aa427484338d0a723b90eba4aa978f5 the CallResolver stopped resolving the variables h* and f*.

In that commit an if/else cascade was changed into a switch/case, that turned
```java
else if (variableName.startsWith("h")) {
  result = getReferenceContent(variableName.substring(1),
  this.request.getHostRef());
}
```
into a case within a switch statement:
```java
switch(variableName) {
   case "h": 
      return getReferenceContent(variableName.substring(1), this.request.getHostRef());
}
```

Obviously this broke variable detection and resolving as a switch parameter of `"hh"` can never fulfill the case condition `"h"`.

As far as I could find out the variables h* and f* are no longer resolved due to that change.
In our case this broke the redirection of "/" to an inbound route to "{hh}/static/index.html" using an instance of Redirector and thus prevents us from upgrading to the newest bugfix release Restlet-2.3.9.

**Comment by thboileau** [comment]
Many thanks for pointing this regression!
The fix will be part of new 2.3.10. We expect to ship it quite soon, maybe next week.
Does it fit your needs?
