### ISSUE TITLE
typo in agent.properties file triggers lots of logging

### ISSUE THREAD

**Issue by ArjohnKampman** [restlet/restlet-framework-java#1262]
The fix for #1238 introduced a new issue due to a typo in the agent.properties file. This file now contains "{a,gentOs}" for Firefox for Windows; where the comma was likely added by accident. As a result, all requests to the server now log a warning "An invalid character was detected inside a pattern variable : null".

**Comment by thboileau** [comment]
thanks @ArjohnKampman I feel sorry for this mistake.

**Comment by thboileau** [comment]
the fix will be part of version 2.3.10, coming soon.

**Comment by thboileau** [comment]
Hi @ArjohnKampman version 2.3.10 has been released.
Could you confirm it fixes the bug?

**Comment by ArjohnKampman** [comment]
@thboileau The problem has been resolved in 2.3.10. Thanks for the rapid response!
