### ISSUE TITLE
Certain concurrent responses have incorrect headers

### ISSUE THREAD

**Issue by adolski** [restlet/restlet-framework-java#1263]
I have a Restlet 2.3.8 JSE server application running in an embedded Jetty (9.3.10). In my Application subclass constructor I initialize a CorsService as follows:

```java
CorsService corsService = new CorsService();
corsService.setAllowedOrigins(new HashSet<>(Collections.singletonList("*")));
corsService.setAllowedCredentials(true);
this.getServices().add(corsService);
```

When I send 100 concurrent requests in a web browser, most of them succeed with the expected response, but a few of them have missing/incorrect response headers.

Below is a page that will get this to happen pretty reliably for me. Usually 4-6 of the responses are not as expected (also they are missing CORS headers which causes the browser to block them).

```html
<!DOCTYPE html>
<html>
  <head>
    <script type="text/javascript">
    function getAsync(url, callback) {
      var xmlHttp = new XMLHttpRequest();
      xmlHttp.onreadystatechange = function() {
        callback(xmlHttp.responseText);
      }
      xmlHttp.open('GET', url, true);
      xmlHttp.send(null);
    }

    for (var i = 0; i < 100; i++) {
      var url = 'http://localhost:8182/iiif/2/f50.jpg/full/full/0/default.jpg';
      getAsync(url, function(xmlHttp) {
        //console.log(xmlHttp);
      });
    }
    </script>
  </head>
  <body>
  </body>
</html>
```

Here is what a successful response looks like:

![success](https://cloud.githubusercontent.com/assets/6854505/26471591/d96e3456-4167-11e7-8df1-5f93274eabb4.png)

And here is a "weird" response:

![fail](https://cloud.githubusercontent.com/assets/6854505/26471595/dd93c0a0-4167-11e7-8ac0-b991bfc25141.png)

Any ideas?

**Comment by thboileau** [comment]
I don't know why, but it seems that the request is directly served by Jetty, according to the value of the "Server" header.

**Comment by adolski** [comment]
Indeed -- also, sorry to be unclear, but I should add that this does NOT involve the Restlet Jetty extension (org.restlet.ext.jetty) -- I'm manually initializing an embedded Jetty in code, giving it a WebAppContext handler, and using Restlet's ServerServlet.

Perhaps it is a bug in that Jetty version... I will do more testing.

**Comment by adolski** [comment]
In the process of creating an SSCCE I've replaced my Restlet resource with a plain Servlet and I can get the same thing to happen there. Sorry for the false alarm.
