### ISSUE TITLE
Update restlet-velocity module to support Velocity 2.0

### ISSUE THREAD

**Issue by kinow** [restlet/restlet-framework-java#1270]
Velocity 2.0 has been released, and one of the features in this release is some memory improvement. I'd like to try that on a project that uses Velocity, and see if the performance enhancement would be noticeable.

Would it be possible to update the restlet velocity module to use this latest version, please?

Thanks
Bruno

**Comment by thboileau** [comment]
hello @kinow 
done. Could you check if it works for you?

**Comment by kinow** [comment]
Sorry for the delay @thboileau 

I started to put together a simple app to try to test it https://github.com/kinow/restlet-velocity-performance-test

But I'm having trouble creating a snapshot version to test in this maven project. Tried `mvn install` from the modules folder, but it failed. Then tried `ant rebuild` from the build directory, but some tests are failing too.

Looked at Travis, but the last builds seem to be failing as well.

Is there anywhere from where I can grab a copy of the latest binary with this fix, please?

Cheers
Bruno

**Comment by jlouvel** [comment]
@quilicicf Could you help @kinow out with the build aspect?
