### ISSUE TITLE
Remove extensions that were deprecated in 2.3

### ISSUE THREAD

**Issue by quilicicf** [restlet/restlet-framework-java#1282]
Removal list: 
* e4
* JDBC
* jSSLutils
* ROME
* SDC
* SIP
* XDB
* XStream

> Note: we’ll keep the Apache HTTP Client extension under the deprecated state in v2.4

**Comment by cyberquarks** [comment]
@quilicicf what do you mean by XStream being deprecated? Is that for the client-side or server-side? XStream is still in the latest version.

**Comment by thboileau** [comment]
Hello @cyberquarks 

it means that the Restlet Framework extension based on XStream is dropped.

As a side note, this extension could used on both client and server sides.

**Comment by quilicicf** [comment]
Well, 

It means that the XStream Restlet Framework extension was deprecated in Restlet Framework `2.3` and removed in `2.4`.

This only concerns the extension, not XStream itself and as @thboileau said, the extension was usable in both the client and server side. 

The last version of Restlet Framework that contained the XStream extension was the `2.3.5` as shown in [the maven repository](https://mvnrepository.com/artifact/org.restlet.jse/org.restlet.ext.xstream).

If there is a version `2.4.x` of Restlet Framework that contains the XStream extension, then that would be a bug.

**Comment by cyberquarks** [comment]
@quilicicf why was it deprecated? Something wrong with XStream? XStream is quite handy why remove it?

**Comment by cyberquarks** [comment]
...also removing XStream means you can't use good and useful XStream annotation, like `@XStreamOmitField` etc.

**Comment by jlouvel** [comment]
Please consider Jackson extension instead. Closing as XStream has previously been removed.
