### ISSUE TITLE
Content-Length: 0 in HEAD responses

### ISSUE THREAD

**Issue by adolski** [restlet/restlet-framework-java#1301]
Hi,

I'm using Restlet 2.3.11. I have an `OutputRepresentation` subclass that writes an unknown amount of data to the response OutputStream, so I'm not able to support a `Content-Length` header. GET requests work correctly with no `Content-Length` sent, but HEAD responses always include `Content-Length: 0`.

I've tried calling `setSize(int)` in my representation's constructor, and that does get rid of `Content-Length: 0` but it also sets the response status to 204 No Content.

Just wondering if I'm using the API incorrectly, or is this a bug in Restlet?

**Comment by thboileau** [comment]
hello @adolski 

I'm really sorry for the delay, I'm quite busy these times.

Could you attach a sample test case? I've tried with this annotated resource's method, and it returns a response without the Content-type header.

Here is the annotated method:
```
@Get("json")
public Representation json() {
    return new OutputRepresentation(MediaType.APPLICATION_JSON) {
        @Override
        public void write(OutputStream outputStream) throws IOException {
            outputStream.write("{\"test\":\"test\"}".getBytes());
        }
    };
}
```

And here is the response:
```
HTTP/1.1 200 OK
Content-type: application/json
Server: Restlet-Framework/@major-number@.@minor-number@@release-type@@release-number@
Accept-ranges: bytes
Vary: Accept-Charset, Accept-Encoding, Accept-Language, Accept
Date: Thu, 21 Dec 2017 13:26:19 GMT
```

**Comment by adolski** [comment]
Thanks for looking at this, @thboileau. After looking into it further, I can only get a `Content-Length: 0` header when Restlet is running as a Servlet in Jetty. I don't get one in Tomcat or when using Restlet's build in web server. It might be [this Jetty issue](https://github.com/eclipse/jetty.project/issues/596).

So, I will close this as it looks more like a Jetty bug. Sorry for the false alarm.
