### ISSUE TITLE
p2 of 2.4 is miss metadata file

### ISSUE THREAD

**Issue by hieplq** [restlet/restlet-framework-java#1335]
p2 public at http://p2.restlet.com/2.4/
miss file artifacts.jar and content.jar

**Comment by hieplq** [comment]
osgi Manifest isn't complete.

**Comment by cyberquarks** [comment]
@hieplq you may be interested in joining the "Unofficial Restlet Community" https://gitter.im/restlet-framework/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by jlouvel** [comment]
Closing as we have removed the p2 repository. Moving forward we'll publish 2,5 artifacts to Maven Central
