### ISSUE TITLE
Some OAuth examples might be outdated

### ISSUE THREAD

**Issue by vedina** [restlet/restlet-framework-java#1337]
There is no OAuthAuthorizer class in Restlet 2.3, as in the example

https://restlet.com/open-source/documentation/user-guide/2.3/extensions/oauth

**Comment by cyberquarks** [comment]
@vedina you may be interested in joining the "Unofficial Restlet Community" https://gitter.im/restlet-framework/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by jlouvel** [comment]
@cyberquarks Why not (re-)start an open discussion in the mailing list about an instant messaging? I'm happy to support such an initiative and make something official.

**Comment by flatlanderer** [comment]
@jlouvel apparently @cyberquarks have been blocked here so can't reply. 

And yeah, an official Restlet Channel would be great. Looking at it, https://gitter.im/restlet/home it seems it's just one step away from creating a channel.

**Comment by jlouvel** [comment]
I just wanted to stop to active spamming of many project issues by @cyberquarks (12 similar comments in a few minutes) so we can have a proper conversation in our mailing list: https://groups.google.com/a/restlet.org/forum/#!forum/framework-discuss

I'll start a conversation thread and will unblock @cyberquarks later today to resume the on conversation.

**Comment by jlouvel** [comment]
I've unblocked @cyberquarks for now. Let's continue the Gitter discussion on this dedicated issue:
https://github.com/restlet/restlet-framework-java/issues/1380

**Comment by jlouvel** [comment]
Closing as the OAuth extension is being removed in version 2.5
