### ISSUE TITLE
Deprecated org.restlet.ext.javamail?

### ISSUE THREAD

**Issue by cgatesman** [restlet/restlet-framework-java#1339]
I recently upgraded to Restlet 2.4 to find out that org.restlet.ext.javamail has been deprecated.  Why?  Is there replacement mail support coming?  The deprecation message only says it will be gone in the next major release.

**Comment by cyberquarks** [comment]
@cgatesman I think you can just use a stand-alone Java mail module

You may be interested in joining the "Unofficial Restlet Community" https://gitter.im/restlet-framework/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by jlouvel** [comment]
Hi @cgatesman the issue has been deprecated due to newer/more modern solution to send email via web APIs, such as popular SaaS solutions like Mailchimp, Mailgun, etc. We want to reduce the footprint of the framework to focus on where it adds the most differentiated value.
