### ISSUE TITLE
Restlet Pricing.

### ISSUE THREAD

**Issue by rhonyabdullah** [restlet/restlet-framework-java#1342]
Hello, i found pricing through this [page](https://restlet.com/pricing).
What if i'm using [this library](https://github.com/restlet/restlet-framework-java) for local usage ? Should i pay for the price ?

**Comment by jlouvel** [comment]
The pricing page is for commercial tools from Restlet Platform. The Restlet Framework however is an open source library usable for free according to one of these licenses:
https://restlet.com/open-source/downloads/legal-terms/
