### ISSUE TITLE
2.4 release documentation links are broken

### ISSUE THREAD

**Issue by noahbetzen-wk** [restlet/restlet-framework-java#1343]
[The documentation on the Restlet website only refers to version 2.3.](https://restlet.com/open-source/documentation/tutorials/2.3)

[The 2.4 tag `README`s all have broken links to documentation that doesn't exist.](https://github.com/restlet/restlet-framework-java/tree/2.4.1#learn-more)

**Comment by cyberquarks** [comment]
@noahbetzen-wk you may be interested in joining the "Unofficial Restlet Community" https://gitter.im/restlet-framework/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by jlouvel** [comment]
This has been fixed last year during the migration of the website to the new infrastructure
