### ISSUE TITLE
Is Restlet framework "dead"? 

### ISSUE THREAD

**Issue by cyberquarks** [restlet/restlet-framework-java#1369]
Is Restlet in auto-pilot now? Meaning it is stable not going to be developed for innovation and modern technologies as it continuously lags behind other Java frameworks, which are now reactive and modern. 

Should we migrate our stack away from Restlet since it is not going to be developed the same way as before? 

https://stackoverflow.com/questions/62306808/is-restlet-still-a-viable-java-framework-to-use

**Comment by jlouvel** [comment]
Hi @cyberquarks 

I understand the concerns with lower core team reactivity. We have actually invested a significant amount of resources at the end of last year and early this year to ensure a smooth migration of Restlet Framework to Talend's infrastructure (incl. full Maven repository migration with minimal visible impact, plus website migration to GitHub Pages) and released:

Version 2.4.3 with fixes:
https://restlet.talend.com/documentation/2.4/changelog

Version 2.5 M1 with important clean-up and scope reduction to facilitate ongoing maintenance and evolution:
https://restlet.talend.com/documentation/2.5/changelog

We are currently assessing where we want to drive the framework moving forward beyond 2.5, either with 2.x or 3.x. Some of the technologies we are considering are cloud-native (service mesh, serverless, OAS 3 and alike).

What would you expect in term of enhancements and innovations?

Best regards,
Jerome

**Comment by cyberquarks** [comment]
@jlouvel Hi, 

As a developer of web applications, one would expect the framework we use should be ready for many modern applications, having said that, progressive and reactive applications. Non-blocking I/O, for the most part, should be supported or at least WebSocket so client applications can do a subscription to server-side events. Example implement chat applications with Restlet, etc.

**Comment by ngigiwaithaka** [comment]
Hi  jlouvel ,

I/We am one of those who picked Restlet a couple of years back mostly due to its elegant design.

Compared to a couple of other open source projects, I would suggest perhaps you put more resources into your online presence and having your Engineers active in answering queries and build the online community and with time this community should take off a big support load from your shoulders...

It would also be nice to let us know how the acquisition by Talend portends for future versions of Restlet... Is there still going to be any *significant investment* in the open source versions in the future for instance or are you moving to paid / subscription model?


Regards
Ngigi

**Comment by jlouvel** [comment]
Hi Ngigi,

Thanks for the feedback and suggestions. We definitely have plans to continue the maintenance of the V2 branch and finish the release of V2.5 after the first milestone, with a V2.6 planned that would remove the notion of editions and would be fully Mavenized, including synchronization to Maven central repository and complete clean-up of the code base around its core. This is work that we plan at this stage to tackle in Q4 '20.

In term of a V3, that would be a bigger investment and its something that needs to align with broader Talend roadmap around APIs. This is definitely something considered, but not committed at this point. As you pointed out, it would require some significant presence to resume the community activities beyond the core development work.

We'll keep  you and the community update as our planning progress.

Thanks for your patience,
Jerome

**Comment by cyberquarks** [comment]
@jlouvel It would be great to have Restlet on Stackoverflow, e.g. would be great to have an answer for this:
https://stackoverflow.com/questions/62306808/is-restlet-still-a-viable-java-framework-to-use

Also I did find a lot of [restlet ](https://stackoverflow.com/questions/tagged/restlet) tagged along with NetSuite RESTlet, so I removed like hundreds of it to clean it up and make sure the tag is only used for the Restlet framework.

**Comment by cyberquarks** [comment]
> Hi jlouvel ,
> 
> I/We am one of those who picked Restlet a couple of years back mostly due to its elegant design.
> 
> Compared to a couple of other open source projects, I would suggest perhaps you put more resources into your online presence and having your Engineers active in answering queries and build the online community and with time this community should take off a big support load from your shoulders...
> 
> It would also be nice to let us know how the acquisition by Talend portends for future versions of Restlet... Is there still going to be any _significant investment_ in the open source versions in the future for instance or are you moving to paid / subscription model?
> 
> Regards
> Ngigi

@ngigiwaithaka from what I see community adoption is key to continued Open-source projects, as to how many Restlet-based production apps our out there, we don't know, how about Talend itself, do they use Restlet at all @jlouvel? 

To some like us who have invested a lot of time and effort building apps and systems using this framework, turning back is a hard thing to just do, despite the cloudy future ahead. All in all, what's important now I guess is the fact if the Framework is stable enough to make your ship run for the next 5 years with minimal updates on the framework, why not. Then if you manage to accumulate a big development team, they can just help maintain the framework (maybe) 

A lot of frameworks now are really getting traction, those event-driven frameworks, like Quarkus, et. al. if this is something not on your roadmap then sticking to Restlet would be the best option, I've tried JAX-RS, etc. but IMHO, Restlet offers the best API out there, not just super simple, its maintainable even by few developers. 

Take this for example, https://github.com/divroll/backend it's a BaaS built on top of Restlet which it's code is very self-explanatory. I can imagine if the their developers built it using other framework it would be a mess. Restlet API allows us to write clean API code.

**Comment by cyberquarks** [comment]
@jlouvel Additionally, I think it's time that the Restlet framework to have a Gitter Discussion group, it would greatly help users and developers. It would help make Restlet be more self-sustaining for the community at large (IMHO)

**Comment by jlouvel** [comment]
I did reply to the StackOverflow question posted for consistency. Let's keep this issue open here as it does touch on important questions that still need to be addressed.

**Comment by sblommers** [comment]
Is there still the goal to do a v2.6 branch commit for the mavenized version? Even if it's in concept it would make sense to the community to pick it up.

**Comment by xSAVIKx** [comment]
Hey @jlouvel. Are there any plans to release the v2.5 branch? It looks like 2.5.M1 was released, but a stable version was never released. I can offer some help to make that happen if that's gonna make a difference.

**Comment by jlouvel** [comment]
We have recently resumed progress on the maintenance with an imminent release of version 2.4.4 and active work in the 2,5 branch with a Mavenified build. We'll update the community in the coming days about those progress and feedback collection. Thanks for your patience, but we are picking up pace and working to facilitate the contribution of the community as well.

**Comment by jlouvel** [comment]
I'm going to close this issue. Please use https://github.com/restlet/restlet-framework-java/discussions for ongoing conversations.
