### ISSUE TITLE
Gitter Discussion group for the Restlet Framework

### ISSUE THREAD

**Issue by cyberquarks** [restlet/restlet-framework-java#1372]
I think it's time that the Restlet framework to have a Gitter Discussion group, it would greatly help users and developers. It would help make Restlet be more self-sustaining for the community at large (IMHO)

- Since Restlet is hosted in Github, users and developers can easily be added to the discussion group
- Contributors can help users
- Users can help other users
- It will make Restlet as a community more self-sustaining

**Comment by jlouvel** [comment]
Let's continue the discussion here in the mailing list:
https://groups.google.com/a/restlet.org/g/framework-discuss/c/412FE3KqdWY

I will carry over your comment there, because it does bring some interesting info.
