### ISSUE TITLE
Restlet OAuth Extension is deprecated - will it be removed or replaced by something else?

### ISSUE THREAD

**Issue by markus-ki** [restlet/restlet-framework-java#1375]
Restlet [changelog](https://restlet.talend.com/documentation/2.4/changelog) says that some extension will be removed with the next minor release. I could not find any information if the extension will be removed completely or reimplemented.

If the extension is no longer supported I have to search for another solution.

May somebody have more information about the current situation.

---
Original Post on [StackOverflow](https://stackoverflow.com/questions/63336765/restlet-oauth-extension-is-deprecated-will-be-removed-or-replaced).

**Comment by cyberquarks** [comment]
@markus-ki you may be interested in joining the "Unofficial Restlet Community" https://gitter.im/restlet-framework/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by jlouvel** [comment]
Hi @markus-ki This extension won't be replaced. The rationale is that those security concerns are better handled by adding an API Gateway in front of your Restlet-based application, or deploy them inside a Service Mesh technology. Better separation of concerns, lighter Restlet Framework footprint, making it easier to evolve.
