### ISSUE TITLE
The "Unofficial" Gitter Room for Restlet framework

### ISSUE THREAD

**Issue by cyberquarks** [restlet/restlet-framework-java#1380]
The "Unofficial" Gitter Room for Restlet framework:
https://gitter.im/restlet-framework/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by cyberquarks** [comment]
@jlouvel thanks, it would be great to have a Discussion channel dedicated to the framework, the one I made has some members now, but there's one https://gitter.im/restlet/home which I think is the official account.

**Comment by jlouvel** [comment]
Let's continue the conversation in the mailing list. Here is the relevant thread:
https://groups.google.com/a/restlet.org/g/framework-discuss/c/412FE3KqdWY
