### ISSUE TITLE
Maven restlet non-parseable pom.xml file of type bom

### ISSUE THREAD

**Issue by irina-bostan** [restlet/restlet-framework-java#1425]
When running a `mvn package ` cmd using docker maven image, the build is failing with the following errors:

`[FATAL] Non-parseable POM /root/.m2/repository/xxx_bom/`

**Set-up:**
docker image: maven:3-openjdk-17
maven central repo: https://maven.restlet.org/

![image](https://github.com/user-attachments/assets/fb644c83-b867-4b03-b855-33f98f25b9a2)

**Comment by Sennahoi** [comment]
Would be great to get any feedback if this maven repo is dead forever.

It is referenced e.g. by spring-cloud-contract-parent-3.1.6 and I can only build this when I override the restlet maven repo with a working one.

**Comment by jlouvel** [comment]
Unfortunately, this older Maven repository has been deprecated and turned off several years ago.

Instead https://maven.restlet.talend.com/ should be referenced for version 2.4 of the framework.

Moving forward with version 2.5, we will only publish to Maven Central and eventually remove the current Maven repository.
