### ISSUE TITLE
Port XStream extension to GAE

### ISSUE THREAD

**Issue by thboileau** [restlet/restlet-framework-java#156]
Initial ticket : http://restlet.tigris.org/issues/show_bug.cgi?id=863

**Comment by kerbymart** [comment]
@thboileau @jlouvel Not sure what is the issue here (as it is still Open) I have a library that uses XStream with GAE, perhaps we can integrate it here if needed.

**Comment by thboileau** [comment]
Hello,
thanks for the heads up. I've just tried and it works for me. we can close this issue.
