### ISSUE TITLE
Port of the Atom extension to GWT

### ISSUE THREAD

**Issue by thboileau** [restlet/restlet-framework-java#180]
Initial ticket : http://restlet.tigris.org/issues/show_bug.cgi?id=918

**Comment by thboileau** [comment]
@jlouvel 
I wonder if this ticket is still relevant for the framework

**Comment by Tembrel** [comment]
RSS and Atom seem to be increasingly irrelevant themselves, so I don't that there's much call for a Restlet Atom extension.

**Comment by thboileau** [comment]
thanks @Tembrel for pointing this.
Atom extension will be deprecated in 2.5, and removed in future 2.6
