### ISSUE TITLE
The netty extension does not seem to support chunked encoding.

### ISSUE THREAD

**Issue by thboileau** [restlet/restlet-framework-java#424]
Initial ticket : http://restlet.tigris.org/issues/show_bug.cgi?id=1376

**Comment by jlouvel** [comment]
I've just checked in an experimental HTTP server based on Netty 4.1 in master branch. It should support chunked encoding properly:
https://github.com/restlet/restlet-framework-java/tree/master/modules/org.restlet.ext.netty/src/org/restlet/ext/netty

**Comment by jlouvel** [comment]
Closing as we removed Netty extension previously
