### ISSUE TITLE
Fix Broken Tests for JAX-RS extension

### ISSUE THREAD

**Issue by javamonkey79** [restlet/restlet-framework-java#442]
When the test project is ran, I show many failing unit tests:

<pre>
Results :

Failed tests: 
  testPathClassString(org.restlet.test.jaxrs.core.ExtendedJaxRsUriBuilderTest)
  testPathClassStringEnc(org.restlet.test.jaxrs.core.ExtendedJaxRsUriBuilderTest)
  testFileClient(org.restlet.test.connector.ZipClientTestCase)
  testMultipleServerRequests(org.restlet.test.ext.oauth.MultipleUserAuthorizationServerHttpsTestCase)
  testFormPost(org.restlet.test.jaxrs.services.tests.ProviderTest)
  testMultivaluedMapPost(org.restlet.test.jaxrs.services.tests.ProviderTest)
  testXmlTransformGet(org.restlet.test.jaxrs.services.tests.ProviderTest)
  testXmlTransformPost(org.restlet.test.jaxrs.services.tests.ProviderTest)

Tests in error: 
  initializationError(org.restlet.test.gwt.client.TestClient)
  testRepresentationToObject(org.restlet.test.ext.atom.ConverterTestCase)
  initializationError(org.restlet.test.jaxrs.services.providers.TestContextResolver)
  testPop(org.restlet.test.ext.javamail.JavaMailTestCase)
  testPops(org.restlet.test.ext.javamail.JavaMailTestCase)
  testSmtp(org.restlet.test.ext.javamail.JavaMailTestCase)
  testSmtps(org.restlet.test.ext.javamail.JavaMailTestCase)
  testSmtpStartTls(org.restlet.test.ext.javamail.JavaMailTestCase)
  initializationError(org.restlet.test.bench.TestPostClient)
  initializationError(org.restlet.test.gwt.server.TestApplication)
  initializationError(org.restlet.test.bench.TestPostServer)
  initializationError(org.restlet.test.bench.TestGetClient)
  testJaxbElementGet(org.restlet.test.jaxrs.services.tests.ProviderTest)
  initializationError(org.restlet.test.bench.TestPostChunkedClient)
  initializationError(org.restlet.test.bench.TestGetServer)
  initializationError(org.restlet.test.bench.TestGetChunkedServer)

Tests run: 666, Failures: 8, Errors: 16, Skipped: 1

[INFO] ------------------------------------------------------------------------
[ERROR] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] There are test failures.

Please refer to c:\Users\shaun\restlet-framework-java\modules\org.restlet.test\target\surefire-reports for the individual test results.
[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1 minute 37 seconds
[INFO] Finished at: Sun Mar 11 16:19:17 PDT 2012
[INFO] Final Memory: 26M/62M
[INFO] ------------------------------------------------------------------------
</pre>

**Comment by jlouvel** [comment]
Closing as we are removing JAX-RS in branch 2.5
