### ISSUE TITLE
Encoder failures

### ISSUE THREAD

**Issue by tliron** [restlet/restlet-framework-java#447]
On Restlet 2.1-RC3 I am getting empty encoded entities on particular entities. In my usage I am putting an Encoder before a Directory. Here is some pseudo-code to set it up:

```
var encoder = new org.restlet.engine.application.Encoder(app.context, true, true, app.instance.encoderService)
encoder.next = directory
```

An example of the response headers in Firebug:

```
Accept-Ranges   bytes
Content-Encoding    gzip
Content-Language    en
Content-Location    http://localhost:8080/style/soft-cricket.css
Content-Type    text/css; charset=UTF-8
Date    Tue, 13 Mar 2012 21:27:13 GMT
Expires Tue, 13 Mar 2012 21:37:13 GMT
Last-Modified   Tue, 13 Mar 2012 21:23:20 GMT
Server  Restlet-Framework/2.1rc3
Transfer-Encoding   chunked
Vary    Accept-Charset, Accept-Encoding, Accept-Language, Accept
```

Notes:

1) Setting the Encoder constructor to not encode (false, false) makes this bug disappear.
2) This bug does not occur with the Encoder in Restlet 2.0.11.

**Comment by thboileau** [comment]
As it works, let's close it.
