### ISSUE TITLE
Add better Maven integration

### ISSUE THREAD

**Issue by thboileau** [restlet/restlet-framework-java#519]
Initial ticket : http://restlet.tigris.org/issues/show_bug.cgi?id=672

**Comment by jlouvel** [comment]
Finally, starting with 2.5 RC1, Restlet Framework is published in Maven Central. Thanks all for your interest in making this happen, it took quite a lot of effort to achieve. See announcement https://github.com/restlet/restlet-framework-java/discussions/1434
