### ISSUE TITLE
JAX-RS @Context for HttpServletRequest

### ISSUE THREAD

**Issue by thboileau** [restlet/restlet-framework-java#532]
Initial ticket : http://restlet.tigris.org/issues/show_bug.cgi?id=722

**Comment by InfoSec812** [comment]
I just spent 3 days really excited about how well it was going porting my application from Guice/Jersey/Jetty to Restlet/DeltaSpike and then I hit this problem... VERY SAD.... :(

**Comment by thboileau** [comment]
If you're application is developed  using Restlet, you can still access the current request and headers (see `Request.getHeaders()` method).

**Comment by InfoSec812** [comment]
I am developing using ReSTlet, but I I am using the JaxRsApplication... How do I get the Request object inside of the JAX-RS resource? Is there an injection annotation for that?

**Comment by komasoftware** [comment]
http://restlet.com/technical-resources/restlet-framework/javadocs/snapshot/gae/ext/org/restlet/ext/servlet/ServletUtils.html

public static HttpServletRequest getRequest(Request request)
Returns the Servlet request that was used to generate the given Restlet request.

**Comment by InfoSec812** [comment]
OK, thanks for the help!

**Comment by jlouvel** [comment]
Closing as we are removing JAX-RS in branch 2.5
