### ISSUE TITLE
Add throttling service

### ISSUE THREAD

**Issue by thboileau** [restlet/restlet-framework-java#533]
Initial ticket : http://restlet.tigris.org/issues/show_bug.cgi?id=723

**Comment by 01es** [comment]
Dear @thboileau and @jlouvel,

I have followed on the original discussion and am also in need of a similar to [Jetty QoS filter] (http://www.eclipse.org/jetty/documentation/current/qos-filter.html) solution for throttling.

Is building a custom filter still the best option or is there something already available for Restlet to support request throttling? I do not mind embarking on the task of building such a filter, followed by a pull request once it is ready. Pleas advise.

**Comment by glaforge** [comment]
@01es have you looked at this RF extension regarding rate limitations and such?
http://restlet.com/technical-resources/restlet-framework/guide/2.3/extensions/apispark/firewall
Perhaps it might help?

**Comment by 01es** [comment]
@glaforge no, I haven't. Many thanks for pointing to this extension! A quick look at the documentation suggests that it might be pretty much exactly what's needed to support QoS feature.

Does it make sense to close this issue with a reference to use APISpark firewall as a solution?

**Comment by thboileau** [comment]
Hi @01es , that's fine, let's close the issue.
