### ISSUE TITLE
2.0-snapshot maven repository is empty

### ISSUE THREAD

**Issue by jwhitney31337** [restlet/restlet-framework-java#549]
See: http://maven.restlet.org/org/restlet/jee/org.restlet.ext.servlet/2.0-SNAPSHOT/
(Currently, this shows an empty directory for me in the browser; if this is no longer the case when _you_ view it, then perhaps the issue has been resolved)

What should be there is a population of maven meta-data and jars, as is currently true for
http://maven.restlet.org/org/restlet/jee/org.restlet.ext.servlet/2.1-SNAPSHOT/

**Comment by jlouvel** [comment]
Finally, starting with 2.5 RC1, Restlet Framework is published in Maven Central as well as in GitHub Packages for snapshots. Thanks all for your interest in making this happen, it took quite a lot of effort to achieve. See announcement https://github.com/restlet/restlet-framework-java/discussions/1434
