### ISSUE TITLE
JSON deserialization and type erasure

### ISSUE THREAD

**Issue by maxhille** [restlet/restlet-framework-java#556]
When retrieving JSON data and using the Jackson-Extension, it would be nice to be able to use some mechanism for working around Java's type erasure. 

The following snipped shows how it would look like if we would use Jackson's method.

```java
ClientResource resource = new ClientResource("http://localhost:8182/example");
List<Example> examples = resource.get(new TypeReference<List<Example>>() {});
```

**Comment by maxhille** [comment]
Just noticed this forever-open issue. Closing it because it has probably been superseeded by something else by now.

**Comment by thboileau** [comment]
linked to #924
