### ISSUE TITLE
Restrict connections to the Restlet tunnel server from SDC agents

### ISSUE THREAD

**Issue by ssrini** [restlet/restlet-framework-java#570]
Assume an agent was configured to connect to a tunnel server and The connection parameters were provided. It is required that later we do not want to allow the SDC agent to connect to the tunnel server any more. Reasons could be many, for eg. trial period of that user expired or maybe the user has not paid the current fee etc.  

Require a mechanism to restrict connections to the Restlet SDC Tunnel either based on IP or based on domain.

**Comment by jlouvel** [comment]
Closing as we removed SDC extension previously
