### ISSUE TITLE
org.restlet.ext.jaxrs.internal.wrappers.params.FormParamGetter in 2.1RC(4)

### ISSUE THREAD

**Issue by srichavali** [restlet/restlet-framework-java#571]
class FormParamGetter defined in ParameterList has a member variable defined 'form' which is static. This variable should not be marked as static. When we have a POST method defined with @FormPost annotation and we hit this end-point with a lot of simultaneous requests, there are mismatches in the parsed form params and the MultivaluedMap that has the same params.

**Comment by jlouvel** [comment]
Closing as we are removing JAX-RS in branch 2.5
