### ISSUE TITLE
OpenID extension does not work with Google App Engine

### ISSUE THREAD

**Issue by rhbgames** [restlet/restlet-framework-java#589]
Following the instructions at http://wiki.restlet.org/docs_2.1/13-restlet/28-restlet/404-restlet.html will eventually lead to the error message: "javax.net.ssl.KeyManagerFactory is a restricted class. Please see the Google  App Engine developer's guide for more details".

As documented at http://stackoverflow.com/questions/6977201/how-to-make-an-https-call-on-app-engine the core problem is that openid4java relies upon Apache's HTTPClient, which is not supported by Google App Engine.  

http://code.google.com/p/googleappengine/issues/detail?id=6608 is a request for the GAE folks to allow KeyManagerFactory.

In the opeid4java project, issue 111 is quite similar to this (if not exactly the same).  Also, there is a claim at https://groups.google.com/forum/?fromgroups#!searchin/openid4java/appengine/openid4java/h1tbZXZ4P6Y/v4JbMoX5msoJ that someone has produced a new openid4java jar that will work with GAE.

And finally, https://groups.google.com/forum/?fromgroups#!topic/openid4java/QoWd0YoVUo8 describes a workaround that I (a novice) was able to follow to create an openid4java jar that works with GAE (although it's probably a bit of a hack).

Submitted to keep track of this issue.

https://groups.google.com/forum/?fromgroups#!topic/openid4java/QoWd0YoVUo8 describes a workaround for this

**Comment by jlouvel** [comment]
Closing as we are removing OpenID extension in version 2.5
