### ISSUE TITLE
Fully instantiate annotated ServerResource inside a JaxRs Application

### ISSUE THREAD

**Issue by thboileau** [restlet/restlet-framework-java#610]
As reported by Carl Prittchet (http://restlet.tigris.org/ds/viewMessage.do?dsForumId=4447&dsMessageId=2969455), the current JaxRs extension does not take into account the case of annotated ServerResource, especially, the request and response are not accessible. See if this use case should be addressed.

**Comment by jlouvel** [comment]
Closing as we are removing JAX-RS in branch 2.5
