### ISSUE TITLE
Internal https connector & clap protocol deadlock?

### ISSUE THREAD

**Issue by gitblit** [restlet/restlet-framework-java#620]
I'm having trouble with the internal 2.1-SNAPSHOT/RC5 https connector combined with the clap protocol - large embedded resources (100k css file) seem to deadlock and are never retrieved - the browser times-out after 1 min and then displays unstyled representation/content.  Oddly, the internal http connector works fine.  I launch both http & https connectors in the same process - https never/intermittently serves the css, http does.

I'm not sure if this is related to issue-576.  I can provide a live example of my issue which can be monitored using Chrome developer tools, if a Restlet dev private-messages me for the urls.

**Comment by jlouvel** [comment]
Closing as we are removing deprecated NIO extension in branch 2.5
