### ISSUE TITLE
"invalid Class-Path header in manifest" warning for org.restlet-2.1.0.jar

### ISSUE THREAD

**Issue by szpak** [restlet/restlet-framework-java#698]
I've got following compilation warning using restlet 2.1.0 from Cetral Maven Repo:
invalid Class-Path header in manifest of jar file: $MY_M2_REPO/org.restlet/2.1.0/org.restlet-2.1.0.jar

**Comment by cdancy** [comment]
Seeing this issue with latest versions released. Seems there is an empty Class-Path entry which is causing issues for us. Any reason this Class-Path entry is still there and is it possible to no longer include it?

```
Manifest-Version: 1.0
Ant-Version: Apache Ant 1.9.2
Created-By: 1.6.0_45-b06 (Sun Microsystems Inc.)
Class-Path: 


```

**Comment by thboileau** [comment]
Hi @szpak  and @cdancy 
thanks for reporting this issue. the fix will be part of 2.3.7.
@cdancy , are you seeing blocking issues? If so I can release a new version.
Shamely, I should take time yesterday before releasing 2.3.6...

**Comment by cdancy** [comment]
;) We are blocked on this end. If we extrapolate the release schedule out we might not see 2.3.7 for some time. I could get around this by repackaging the jars with the fixed manifest but that seems hokey...

**Comment by cdancy** [comment]
Any chance we could re-release 2.3.6 or let 2.3.7 go?

**Comment by thboileau** [comment]
Hi @cdancy , Restlet Framework 2.3.7 has been released.

Could you tell us if it fix the bug?

**Comment by cdancy** [comment]
@thboileau noticed it yesterday actually, and tested, and can confirm we are good to go ;) Thanks for the release!

**Comment by dweiss** [comment]
We still get this issue with org.restlet.ext.servlet-2.4.3.jar.
