### ISSUE TITLE
Simple HTTPS-Connector does not start anymore

### ISSUE THREAD

**Issue by ebertmi** [restlet/restlet-framework-java#702]
In Version 2.1.1 and 2.2-M1 and 2.2-Snapshot using HTTPS with the simple framework does not work. I get always a timeout when trying to access my files. Normal HTTP starts via simple-server https does not.

Though also the internal https-connector does not work for me --> always timeouts. See this stackoverflow-post for code details:

http://stackoverflow.com/questions/14187399/restlet-2-1-1-internal-https-connector

**Comment by jlouvel** [comment]
Closing as we are removing Simple extension in version 2.5
