### ISSUE TITLE
OAuth - Storing access tokens using in-memory TokenStore fails on GAE

### ISSUE THREAD

**Issue by rhbgames** [restlet/restlet-framework-java#707]
The org.restlet.ext.oauth.internal.MemTokenGenerator code (2.2, November snapshot) uses:
`private final Map<String, Token> tokenStore = new ConcurrentHashMap<String, Token>();`
to store access tokens.  There is a comment that  says that "Note that token generated will not be persisted after a JVM restart."  (which would be fine with me).

However, in a Google App Engine environment, a new JVM can apparently be created on the fly due to changing load conditions and then the new JVM will not be able to find tokens stored in the old JVM.  At least that is what was happening to me yesterday.  (Also by setting my <threadsafe> setting to false, I could reproduce the problem consistently.)

It seems that memcache should be used to improve the situation (or dbms storage - but I imagine that is more difficult in a "reference" implementation).

**Comment by jlouvel** [comment]
Closing as we are removing OAuth extension in branch 2.5
