### ISSUE TITLE
No release for Netty extension in 2.1.X

### ISSUE THREAD

**Issue by rsertelon** [restlet/restlet-framework-java#723]
Hi :)

I'd like to create a project with the 2.1.1 version of Restlet (in java) on top of Netty, but it seems there's no release of the 2.1.x branch for this extension.

Is it on purpose? (blocking bug) or just an oblivion? :)

Thanks!

**Comment by jlouvel** [comment]
I've just checked in an experimental HTTP server based on Netty 4.1 in master branch:
https://github.com/restlet/restlet-framework-java/tree/master/modules/org.restlet.ext.netty/src/org/restlet/ext/netty

**Comment by jlouvel** [comment]
Closing as we removed Netty extension previously
