### ISSUE TITLE
UriBuilderImpl does not encode brackets ([ and ])

### ISSUE THREAD

**Issue by tmortagne** [restlet/restlet-framework-java#725]
Here is an example of code that use to work perfectly well and is broken in 2.1.1:

```
UriBuilder.fromUri("http://xwiki.org/rest").path("/wikis/{wiki}").build("[bracket]");
```

This produces: java.net.URISyntaxException: Illegal character in path at index 20: http://xwiki.org/rest/wikis/[bracket]. Looks like the bracket is not encoded anymore and as far as I can see in debug this is because org.restlet.data.Reference.isValid('[') returns true.

**Comment by jlouvel** [comment]
Closing as we are removing JAX-RS in branch 2.5
