### ISSUE TITLE
injecting JaxRsApplication instance via Context annotation into Jax-Rs resource

### ISSUE THREAD

**Issue by johannbarbie** [restlet/restlet-framework-java#735]
Hi everyone,

I'm trying to get [Swagger](http://developers.helloreverb.com/swagger/) to document my rest service. To do so you basically register their api-listing resource with your Jax-Rs application, and off you go.

Unfortunately, their [implementation](https://github.com/wordnik/swagger-core/blob/master/modules/swagger-jaxrs/src/main/scala/com/wordnik/swagger/jaxrs/ApiListing.scala) requires the injection of two objects:
- javax.servlet.ServletConfig
- javax.ws.rs.core.Application

First one is hard to satisfy, if you don't run inside a web container, so I opened an issue [here](https://github.com/wordnik/swagger-core/issues/146).

The second one gives me this:
_org.restlet.ext.jaxrs.internal.exceptions.IllegalMethodParamTypeException: class javax.ws.rs.core.Application must not be annotated with @Context_

The Application dependency I would consider quite handy to be injected, but couldn't find a way looking at [ConextInjector.java](https://github.com/restlet/restlet-framework-java/blob/master/modules/org.restlet.ext.jaxrs/src/org/restlet/ext/jaxrs/internal/wrappers/params/ContextInjector.java)

Please give me a hint how to do that. I would be happy to contribute to Reslet, I used it extensively in my projects! :)

**Comment by jlouvel** [comment]
Closing as we are removing JAX-RS in branch 2.5
