### ISSUE TITLE
Using oauth client_credentials,The generated token does not has username,so TokenVerifier will throw JSONException.

### ISSUE THREAD

**Issue by bestree** [restlet/restlet-framework-java#768]
hi,when i using the client_credential flow of oauth,i found that the token generated doest not has a username,so tokenverifier  will think it invalid.I wonder whether it is a problem.

try {
            ClientInfo clientInfo = request.getClientInfo();
            clientInfo.setUser(new User(jsonResponse.getString(OAuthServerResource.USERNAME)));
            clientInfo.setRoles(Scopes.toRoles(jsonResponse.getString(OAuthServerResource.SCOPE)));
        } catch (JSONException ex) {
            return RESULT_INVALID;
        }

Thank you for your attention.

**Comment by jlouvel** [comment]
Closing as we are removing OAuth extension in branch 2.5
