### ISSUE TITLE
OAuthProxy RedirectURI Behavior

### ISSUE THREAD

**Issue by msvens** [restlet/restlet-framework-java#775]
The current version (in the main branch) of the OAuthProxy relies on the redirectURI to be set prior to using the Proxy. This can be problematic if the OAuthProxy sits infront of a router in which case the redirectURI might change. I suggest we add some code to handle this in case the redirectURI is not set. Something like the following might work

```
protected OAuthParameters createAuthorizationRequest(Request request) {
    OAuthParameters parameters = new OAuthParameters()
            .responseType(ResponseType.code)
            .add(CLIENT_ID, getClientId());
    if (redirectURI != null) {
        parameters.redirectURI(redirectURI);
    }
    else{
      parameters.redirectURI(request.getResourceRef().getHostIdentifier()
              + request.getResourceRef().getPath());
    }
    if (scope != null) {
        parameters.scope(scope);
    }
    return parameters;
}
```

And do the same for createTokenRequest

**Comment by jlouvel** [comment]
Closing as we are removing OAuth extension in branch 2.5
