### ISSUE TITLE
OAuth State Validation

### ISSUE THREAD

**Issue by msvens** [restlet/restlet-framework-java#776]
I have observed a problem with state validation in the new OAuthProxy class. I am not sure if the problem lies in the OAuthProxy or somewhere. Please indicate if anyone else has this problem.

State validation works by storing an identifier in the context attributes so that it can compare that later with the state information in the request parameters, like this:

 CookieSetting cs = new CookieSetting("_state", sessionId);
        response.getCookieSettings().add(cs);

```
    getContext().getAttributes().put(sessionId, state);
```

Later when comparing the OAuthProxy simply do the following:

 String sessionId = request.getCookies().getFirstValue("_state");
        String state = (String) getContext().getAttributes().get(sessionId);
        if (state != null && state.equals(params.getFirstValue(STATE))) {
            return;
        }
        // CSRF detected
        throw new Exception("The state does not match.");

Whenever you are accessing your site with a trailing / everything works find but when you remove it breaks. So for instance, in my case http://www.mellowtech.org/graphs/s/fb/network/ would work find but http://www.mellowtech.org/graphs/s/fb/network does not work. When I debug I can see that in the latter case the context does not hold any state information, i.e state == null.

I suspect there is a problem with contexts here. Any suggestions?

**Comment by jlouvel** [comment]
Closing as we are removing OAuth extension in branch 2.5
