### ISSUE TITLE
Allow to turn off header cleaning in Redirector for server-side redirects

### ISSUE THREAD

**Issue by tliron** [restlet/restlet-framework-java#799]
Currently, the Redirector always cleans request and response headers in the serverRedirect method. However, there are many use cases for which headers need to be preserved. My solution was to override Redirector to provide this functionality, but I think it's easy and useful to add it to the Restlet Redirector class. I suggest calling it "isCleaning".

You can see my implementation here:

http://code.google.com/p/prudence/source/browse/components/prudence/source/com/threecrickets/prudence/util/ResolvingRedirector.java

**Comment by thboileau** [comment]
Hello @tliron , we will take this issue in the 2.3.2 release.

**Comment by thboileau** [comment]
Fixed also a bug that prevent to detect if a header is standard or not.
