### ISSUE TITLE
Consider setting up automated builds

### ISSUE THREAD

**Issue by BryanHunt** [restlet/restlet-framework-java#8]
We should consider setting up Jenkins for all of the builds.  It could easily manage all of the editions, archives, and releases.  It also integrates nicely with JaCoCo, FindBugs, and Sonar.
# workload: 4h

two kind of tasks:
- simple build targetted at each commit for checking code
- daily snapshot published

**Comment by jlouvel** [comment]
GitHub Actions is now used to automate build of Restlet Framework.
