### ISSUE TITLE
Update to new version of HttpComponents

### ISSUE THREAD

**Issue by tomassommar** [restlet/restlet-framework-java#800]
Currently, the Restlet Framework is using a quite old version of HttpComponents, that is, version 4.1.1. Many other libraries has updated to use later versions of HttpComponents not compatible with the old 4.1.1 version. This aggrevates the JAR hell commonly associated with Java. Thus, it would be great if the Restlet framework could update to use a current version of HttpComponents (and current versions of other libs in general.

Thanks!

**Comment by thboileau** [comment]
done in RF 2.3.
HttpClient has been removed in 3.0 in favor of the netty extension.
