### ISSUE TITLE
+ symbol (%2b) converted incorrectly when media query parameter is used 2.1.4

### ISSUE THREAD

**Issue by thatsnotright** [restlet/restlet-framework-java#804]
I may be misconfiguring or understanding the code, but I believe when query parameters are used the TunnelFilter class is invoked, and that eventually results in this code being invoked:

```java
            // Update the query if it has been modified
            if (queryModified) {
                request.getResourceRef().setQuery(query.getQueryString(null));
            }
```
which results in this code from Reference
```java
        if (queryString) {
            result = result.replace("+", "%20").replace("*", "%2A")
                    .replace("%7E", "~");
        }
```
because no encoding type is set from the TunnelFilter call to properly convert a + to a %2b instead of a %20 because at this point the parameter should have been fully decoded all of the + symbols should be a legitimate + symbol and not a space, which means it should be re-encoded to a %2b

In my case I am passing a date-time of the form: 2013-11-26T03:45+1300 

If I use this url:
http://localhost:8087/path/to/resource?start=2013-11-26T03%3A45%2B1300&end=2013-11-26T04%3A45%2B1300

I get back the response I expect.  If I use this url:
http://localhost:8087/path/to/resource?start=2013-11-26T03%3A45%2B1300&end=2013-11-26T04%3A45%2B1300&media=xml

The action receives query parameters with a space instead of a + for the UTC offset, like so: 2013-11-26T03:45 1300

Has anyone verified that query parameters are being passed correctly when the TunnelFilter is used and one of the query parameters contains an encoded + symbol?  Is there something I am missing in my configuration or misunderstanding?

Thanks in advance.

**Comment by thboileau** [comment]
Thanks @thatsnotright , I've fixed the issue, and added a test case.
It will be part of release 2.3.3.
