### ISSUE TITLE
Restlet consumes all system resources (The thread blocked at the cyclic barrier has timed out)

### ISSUE THREAD

**Issue by wimjongman** [restlet/restlet-framework-java#805]
## The issue

When using restlet version 2.1.4 we always manage to get restlet to run in a loop which consumes all of our resources. The loop always starts with the following error:

```
Nov 26, 2013 3:51:06 PM org.restlet.util.SelectionRegistration block
WARNING: The thread blocked at the cyclic barrier has timed out
java.util.concurrent.TimeoutException
    at java.util.concurrent.CyclicBarrier.dowait(CyclicBarrier.java:250)

(more stacktrace in the next comment)
```

When switching on tracing at this point we see an endless logging going on which I will also put in a separate comment.

We have to restart tomcat to recover.
## Background

We are running our OSGi based webapp inside Tomcat. We first ran restlet in its own server inside the webapp by using apache http server which was directly addressed by our web clients through an alternative port. HTML and javascript libraries are served by Tomcat and the javascript communicates with the embedded http server running restlet.  

When this caused the mentioned problems we switched to a slightly different strategy by using the restlet extension servlet to route to the internal http server. As we expected, by the nature of the change, this did not solve the problem.

When searching on the internet there were several mentions of the same problem [1][2][3] but unfortunately there was no answer. 

I hope we have provided you with enough information.

[1] http://stackoverflow.com/questions/14984595/attaching-apache-http-client-to-restlet-client
[2] http://restlet.tigris.org/ds/viewMessage.do?dsForumId=4447&dsMessageId=3041588
[3] http://www.coderanch.com/t/605414/Web-Services/java/RESTlet-slower-Axis

**Comment by jlouvel** [comment]
Closing as we are removing deprecated NIO extension in branch 2.5
