### ISSUE TITLE
JaxRs multivalue query-params gives list with null element

### ISSUE THREAD

**Issue by srs** [restlet/restlet-framework-java#922]
I do the following in a JaxRs resource (using Restlet JaxRS extension):

``` java
@GET
@Produces("text/plain")
public String doSomething(@QueryParam("key") List<String> keys)
{
  return keys.toString();
}
```

When this is requested with multiple keys, then the array is returned as you would expect. Requesting the endpoint with key=a&key=b gives [a,b] as a result.

But, when no key is used in the url I would expect an empty list, but instead Restlet gives me a list with one "null" entry ([null]). Is this the right behaviour? Jersey gives me what I expect - an empty list.

Probably a very easy fix, except this will probably break some code that is buildt upon the unexpected behaviour.

**Comment by jlouvel** [comment]
Closing as we are removing JAX-RS in branch 2.5
