### ISSUE TITLE
Restlet Framework eclipse installation

### ISSUE THREAD

**Issue by mcartaud** [restlet/restlet-framework-java#938]
The installation of Restlet Framework cannot be completed through the eclipse p2 repository :

![capture du 2014-08-06 10 04 07](https://cloud.githubusercontent.com/assets/2682778/3830624/fb611f4a-1d8b-11e4-95e3-5282e45e45bc.png)

**Comment by thboileau** [comment]
Hi @mcartaud, thanks a lot for reporting this issue, and sorry for the late response.
I was able to install the 2.3.2 release.
feel free to reopen it.
