### ISSUE TITLE
@ApplicationPath annotation supported?

### ISSUE THREAD

**Issue by RovoMe** [restlet/restlet-framework-java#949]
JAX-RS allows to define a base-path of a REST application via the [`@ApplicationPath`](http://docs.oracle.com/javaee/7/api/javax/ws/rs/ApplicationPath.html) annotation to a subclass of `javax.ws.rs.core.Application`. 

However, having a custom `javax.ws.rs.core.Application` which runs in a Jetty server (no servlet-container) this annotation is not considered and the path contained in the value of the annotation is not added before the path of the resources held by that application.

Is this behavior intended and the annotation only supported by servlet-containers? Defining the base context-path is possible, though, using a code sample like

```
...
// add JAX-RS support in Restlet
JaxRsApplication jaxRsApplication = new JaxRsApplication(server.getContext());
// add the JAX-RS application containing the @ApplicationPath annotation to the JaxRsApplication container
jaxRsApplication(application)
// define the base path the JAX-RS service will work on
String basePath = "/rest";
component.getDefaultHost().attach(basePath, jaxRsApplication);
...
```

where `basePath` is the actual base path the service should use. As `VirtualHost` also provides an `attach(Restlet)` method I would have hoped that this method actually was able to attach the value of the `@ApplicationPath` annotation and provides capabilities via `attach(String, Restlet)` to overrule the base application path if needed.

**Comment by jlouvel** [comment]
Closing as we are removing JAX-RS in branch 2.5
