### ISSUE TITLE
ext.jaxrs SecurityUtil not finding certificates

### ISSUE THREAD

**Issue by stnagel** [restlet/restlet-framework-java#981]
I'm using the JAX-RS extension in a servlet container and injecting a @Context SecurityContext into my Resource to gain access to the subjectDN of the the client's certificate.  I've included a CertificateAuthenticator and it appears that the certificate information is making it correctly into the Request.ClientInfo Principals and User fields.  However, the JAX-RS SecurityUtil class is trying to extract the certificate information using the "org.restlet.https.clientCertificates" attribute on the Restlet Request and nothing is returned.  It appears that SecurityUtils should be using Request.getClientInfo() and then either getCertificates(), getPrincipals(), or getUser().

I've found documentation, javadocs, and blog posts that refer to the "org.restlet.https.clientCertificates" Request attribute, but I don't see anyplace in the code where it is actually being set.  Is this Request attribute deprecated/obsolete in favor of the Request.getClientInfo() fields referred to above?

**Comment by jlouvel** [comment]
Closing as we are removing JAX-RS in branch 2.5
